### ISSUE TITLE
[reborn] idea how make mode selection

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#101]
Hi, if you player overthrow you should know there's different maps in same custom game, every map called with proper setting like:

solo
duo
triple

so you can split all pick, all randoms etc. modes with maps

**Comment by ohos** [comment]
of course LOD has much more settings and it's impposible to split them all, but it would be perfect to split at least most popular settings like:

all pick, all random, single draft (3 types)
wtf = yes/no (2 types)
number of spell slots 4,6,12 (3 types)
then it would be 18 total combinatios because 3 * 2 * 3=18

**Comment by ash47** [comment]
A simpler version of this may be considered in the future.
