### ISSUE TITLE
[bug] Mana break, geostrike, desolate and etc doesn't work on illusions

### ISSUE THREAD

**Issue by crabovan** [ash47/LegendsOfDota#104]
Title says it. I've done this build many times, but today (26 june) it stopped to work. I'm also tested it few times in private lobby to ensure.
(Reborn)

**Comment by ash47** [comment]
LoD hasn't been touched for almost a week now, starting to fix stuff now, as it's finally my free time <3

**Comment by TheRisen41** [comment]
T have noticed the same thing. The problem is that the illusions dont have any abilities
