### ISSUE TITLE
Bug/Weird interaction between Holy Persuasion + Multicast

### ISSUE THREAD

**Issue by chrislafeken** [ash47/LegendsOfDota#105]
As you can see in the photo, If you use Holy Persuasion near an enemy tower and it Multicasts, it has a chance of Persuading the tower. Becasue it is yours now, you cannot attack it. BUT because it WAS the enemies' tower, you cannot further push the lane, because their next tier tower is still invulnerable. Regardless, the issue at hand is that Towers should not be persuadable.

![2015-06-26_00002](https://cloud.githubusercontent.com/assets/13072251/8389977/95031a70-1c34-11e5-8eef-d07f7a109764.jpg)

**Comment by ash47** [comment]
XD

**Comment by chrislafeken** [comment]
Ridiculous trolling is it not? Troll your own mates by preventing ally pushes!

**Comment by ash47** [comment]
This if fixed now <3 Also took the opportunity to fix the particle errors with multicast

**Comment by chrislafeken** [comment]
Nice! I have to say, your mod is on the leaderboards for most popular for a reason. Extremely enjoyable just because of its high custom options list. But the other reason is because its among the most updated. Patching things same day as you hear them is quite dedicated work rigth there

**Comment by Veroalla** [comment]
I agree with this guy above
