### ISSUE TITLE
Potential skills to add to troll combo list

### ISSUE THREAD

**Issue by chrislafeken** [ash47/LegendsOfDota#106]
Gyro's Call Down + Rearm: Global ult, isn't that enough said?
Tombstone + Rearm: Until Tombstone isn't showing errors that can't be attacked, it's too strong a combo.
Netherward + Rearm: Pierces spell immunity, en masse makes this too ridiculous.

**Comment by ash47** [comment]
Added calldown + rearm, I don't think the other two are sooooo bad though, needs others people's opinions though

**Comment by chrislafeken** [comment]
Sounds fine by me, just suggestions in case they might be overlooked. I mean, 100+ heroes makes for a lot of skills to mull over. Sometimes things get overlooked~

**Comment by chrislafeken** [comment]
I thought of anotheI came across a really troll combo during a round.
Divided we Stand plus any of the Bash passives. Alone, bash is not too big of a deal, Divided we Stand + Bash is a problem. DWS + an aghs means 5 heroes with bash on each, 25% chance to bash per clone means you aint moving once they hit you.

Id also argue because each bash skill says it is incompatible with Sukll basher, they should be added to troll combo list with each other. If they cant stack with the item of the same name, they shouldnt with each other either.

**Comment by ash47** [comment]
The original idea behind troll combos was to simply ban stuff that can't be
countered, don't want to ban every spell that works well with other spells.

For example, there's no real way to counter rearm + thunder God's wraith

The zuus static field plus a toggle spell isn't really counterable

I think the way you counter a perma basher is to kill them before they can
attack you, or to disable them, just hex, hex, hex, this will work if you
have multicast too.

The other way around it, don't travel alone, take a friend and you can the
permabasher

**Comment by ohos** [comment]
as a tip - just enable "host ban" and ban everything you don't like ^^

**Comment by ash47** [comment]
The combos listed have either been added, or they havent been added. Not much more I can do here.
