### ISSUE TITLE
Skills who function improerly or are innacurate when Double max skill lv enabled

### ISSUE THREAD

**Issue by chrislafeken** [ash47/LegendsOfDota#107]
So for the most part im happy tombstone is fixed and all. However it does have a bug when Double max skill lvls is enabled. Leveling it to lv5 or higher bugs it so you cannot use tombstone, using it consumes mana and starts the cooldown but no tombstone appears. No zombies will spawn either, in case it was jsut a graphical bug. For all intents and purposes it has no effect. Though upon trying it will destroy trees, so it is trying to use the skill. No picture this time, but I'm sure it is easily reproducable

**Comment by chrislafeken** [comment]
Adding to the list, Eidolons from Enigmas skillset have the same problem. Though I will say they still kill the target unit and give you the gold. So it is TRYING to use the skill and getting halfway through using it. But no eidolons pop out

**Comment by chrislafeken** [comment]
Another skill I ntoiced this with is Abbadon's ult borrowed time. With a scepter it should last 10 seconds at max and it does, but the cooldown listed says 10 secondsbut is actually 40. Either the tooltip is wrong, or the cooldown is ignoring the skill rank

**Comment by ash47** [comment]
I think I removed this option all together, so, this is no longer an issue ;)
