### ISSUE TITLE
[request] reborn - advanced settings for spells multiplier and few bugs

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#111]
Hi, would be nice to split hero spells multiplier into separate settings:

1. damage multiplier
2. cast range multiplier
3. AOE skills range multiplier
4. movement speed
5. attack speed

would be nice also add item multipliers and numbers like x2, x3, x4, because x5 sometime really too much

Bugs to fix:

1. showed hp on creeps/tower/buildings isn't increased visually, but they are still increased
2. eyes in the forest - ability description show increased range of sight, but it isn't really increased when applied to tree
3. thirst - gives bonus immediatly on lvl 1 and each next, doesn't depend on real enemy hp

**Comment by chrislafeken** [comment]
Adding on to that, I'd like to see Ability max lvls separate too, so you can have a 5x multiplier to the spells, AND double its max lvls for example.

-Can confirm have reproduced the Eyes of the forest having normal vision range even though description showed a higher amount with 5x and higher multipliers to spells.

**Comment by ohos** [comment]
just offtop, can i somehow see issues on LOD here from other people? i can only open list of mine

**Comment by kacperpl1** [comment]
here? https://github.com/ash47/LegendsOfDota/issues

**Comment by ohos** [comment]
ty, found

**Comment by ash47** [comment]
Good luck with that, the compiler originally did that and there are so many
spells it literally adds 30 seconds+ to load time!

The trouble is that you need to have one ability per variant, let's say
there are 400 abilities, then let's say you want to change the range and
damage of each separately, let's say you get 4 levels of damage and 4
levels of range, that's 400 x 4 x 4 = 6400 spells you need already, then,
if you wanted to adjust the cool down with 4 levels, times that by 4, want
to adjust the mana cost? Another x4, and if you wanted more than 4 choices
per variant? The number would be even larger

**Comment by ash47** [comment]
This will never be added, spell multiplier and item multipler are being removed due to compatibility issues.
