### ISSUE TITLE
[request] when global unique spells enabled - please mark already taken abilities

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#114]
when global unique spells enabled - please mark already taken abilities on board:

with color
with any mark
anything else

**Comment by ash47** [comment]
True

**Comment by ash47** [comment]
This is a good idea, will consider adding it to a future update.

**Comment by ash47** [comment]
This will likely be implemented shortly into the new UI.

**Comment by ash47** [comment]
This has since been implemented in the newUI :)
