### ISSUE TITLE
[idea] Invisibility ban option

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#115]
I think it could be a good idea to set a group of invisibility spells as a host option ban. The reason is there are many spell combos that are totally over powered if you can jump in and out of invisibility. Additionally a game where half of the players use perm invis or skeleton walk ends up whole groups hunting non-invis players leading them to abandoning the match.

**Comment by ohos** [comment]
then also "all blinks/moving" abilities too, by "moving" i mean skewer, disraptor's return, void's and slark's "blinks", ball lightning and so on, if you wish full list, just let me know

**Comment by kacperpl1** [comment]
What I mean you can control where enemy is when you see him wandering on other lanes. When you face whole invis team you have no idea whether they are grouping up against you or not + invis makes it easy in early game to approach enemy with sick damage spells.

**Comment by ohos** [comment]
agree, same for blinks, because QOP's blinks + 5 stuns (6 spells usual game) make same problem, other people can just hide behind trees waiting someone come

**Comment by ash47** [comment]
This will likely be added eventually, since i know a lot of people just ban all this stuff anyways.

**Comment by KaupoKytaru** [comment]
Funny...

"Ash47  [author] 17 hours ago 
There is an option to ban them XD It's called enabling bans XD"

Same issue different answer!

**Comment by Veroalla** [comment]
> @ash47 
There is an option to ban them XD It's called enabling bans XD

Yep, Ash is hilarious like that <3

**Comment by ash47** [comment]
This option was actually added

**Comment by Veroalla** [comment]
Why is shadow blade and silver edge not banned?

**Comment by ash47** [comment]
Because that option relates to skills lol
