### ISSUE TITLE
[request] make "ready" button on spell selection shining

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#118]
make "ready" button on spell selection shining, it would help people understand it's required to press, but when player ready, would be nice to remove shining from this button

**Comment by TheRisen41** [comment]
or just make the button bigger and place it somewhere else

**Comment by ohos** [comment]
this may help too, but due already big spell pick interface, shining animation won't require any extra space and probably attrack attention better ^^

**Comment by ash47** [comment]
This will likely be implemented at some stage.

**Comment by ash47** [comment]
This has been implemented in the new UI, it will roll out when it's ready.
