### ISSUE TITLE
Aftershock + Infest(Control) abuse

### ISSUE THREAD

**Issue by bladespinner** [ash47/LegendsOfDota#123]
Hello, after casting Infest on a unit, controlling it and then exiting it the hotkey for infest remains bind to the Control ability which has no cooldown or manacost, is spamable, and triggers aftershock. Clicking the infest ability with the mouse button triggers infest correctly as opposed to the hotkey which triggers "Control". See the combat log:
![combat-log](https://cloud.githubusercontent.com/assets/3865336/8439486/16f5b220-1f75-11e5-98d6-52880ad74e2c.png)

**Comment by ash47** [comment]
Cool, I have banned infest + aftershock, which should deal with that issue <3 WIll roll out next update.
