### ISSUE TITLE
Can't learn Invoker skill "Deafening Blast"

### ISSUE THREAD

**Issue by fenix008** [ash47/LegendsOfDota#127]
You can not learn this ability, It does not have a minimum level for the study.

Screenshot: http://puu.sh/iMOv1/8d0c579674.jpg

**Comment by ash47** [comment]
I have decided to just remove it from the pool of pickable skills until it can be fixed, having failed to fix it just now :/

**Comment by ash47** [comment]
Will roll out next update.
