### ISSUE TITLE
Bug with 3rd "passive" skill Storm Spirit

### ISSUE THREAD

**Issue by fenix008** [ash47/LegendsOfDota#128]
You can get Storm Spirit's 3rd "passive" skill without learning it.

Screenshot: http://puu.sh/iMOzx/383205a885.jpg

**Comment by ash47** [comment]
Should hover over it, chances are, it does no damage...

**Comment by SunbleachedAngel** [comment]
It is like Slark's ult

**Comment by ash47** [comment]
It won't deal any damage, it's purely cosmetic.

**Comment by ash47** [comment]
Don't really care at the moment, as it is only cosmetic, I'll leave it open as I may fix at some stage.
