### ISSUE TITLE
[request] random lane paths

### ISSUE THREAD

**Issue by fenix008** [ash47/LegendsOfDota#130]
I have one idea, what about "random" line paths? i remember it was in...."Frota" or somewhere else, but it was fun :)

Screenshot sketch: http://puu.sh/iMP4m/58de0a9d54.png

**Comment by ash47** [comment]
This could potentially be added in the future, but it is not a high priority right now.

**Comment by fenix008** [comment]
Yes, i understand it. Thank you for answer :)

**Comment by ash47** [comment]
Moving away from the idea of crazy options, this may be conconsidered in the future, but wont be added now.

**Comment by fenix008** [comment]
how about now ?
