### ISSUE TITLE
102% Damage Reduction

### ISSUE THREAD

**Issue by Gorshin07** [ash47/LegendsOfDota#131]
By combining bristleback+burrow+dispersion or (40% dmg reduction from behind/40%dmg reduction when burrowed/22% dmg reduction from dispersion) it is possible to achieve 102% dmg reduction as the reductions stack additively. This is not gamebreaking by itself as being invincible is great and all but you are unable to actually do anything. HOWEVER if you were to also pickup ball lightning and teleportation, you could teleport just outside the enemy fountain, ball lightning into the fountain and then turn around (by abusing the ball lightning frames of invincibility). Because most hosts use the anti fountain camping setting this means that you will insta kill entire teams of enemies and lock them in their base if they ever die. I AM AWARE THAT THIS IS SUPER SPECIFIC. But it is a troll combo and I think should be removed from the game. Thanks!

**Comment by ash47** [comment]
Fixed, will roll out next update
