### ISSUE TITLE
Item Ability CDs Not Working

### ISSUE THREAD

**Issue by aschmahmann** [ash47/LegendsOfDota#133]
For example if you select Wand as an ability and have aftershock you can permastun. It seems reasonable to have item abilities work with aftershock, but they should have their standard cooldowns, instead of Wand having no cooldown.

**Comment by SunbleachedAngel** [comment]
All items as skills are buged

**Comment by ash47** [comment]
I'll probably just remove items as abilities.

**Comment by ash47** [comment]
This will be fixed when the new UI rolls out.
