### ISSUE TITLE
dispersion+borrow+Bristleback = 102% damage reduction

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#135]
dispersion+borrow+Bristleback = 102% damage reduction

what they do? usually teleport to fountain with ghost scepter, borrow under OP fountain and one-shot everyone in range of 1000 (from dispersion) because dispersion spread damage before any reduction and fountain stack fury swipes very well

**Comment by ash47** [comment]
Fixed, will roll out next update :)
