### ISSUE TITLE
Autocast abilities doesn't work

### ISSUE THREAD

**Issue by MehrunesRazor** [ash47/LegendsOfDota#136]
I think that the title explains it. Alt+Hotkey doesn't turn on the autocast abilities. I even tried to change the key to use the autocast automatically. (e.g. If it was Alt+Q, I changed it to just Q but that didn't work either.)

**Comment by ash47** [comment]
Try right clicking the ability slot? Will look into the hot key issue

**Comment by ash47** [comment]
I think this is fixed? They seem to auto cast for me...
