### ISSUE TITLE
Aegis doesn't work correctly

### ISSUE THREAD

**Issue by Raendan** [ash47/LegendsOfDota#139]
When you die with aegis instead of having the 5 second respawn it uses your regular death timer.

**Comment by ash47** [comment]
I've fixed this so many times now :/ no idea why it keeps coming back ha ha

**Comment by Jexah** [comment]
Since this is still open, just thought I'd mention that I have only ever seen this when the respawn timer is modified in the options.

**Comment by ash47** [comment]
There is a note to fix this ;) hopefully soon
