### ISSUE TITLE
Auto Disconnect Problem

### ISSUE THREAD

**Issue by wwa143** [ash47/LegendsOfDota#144]
Eversince the last update, this game cannot start at all.... once we are in the map, in less than 30 secs everyone disconnect. Imba 10 v 10 has no problem... so I think is just this game LegendsofDota... pls fix thank you :D

**Comment by ash47** [comment]
I just pushed a new patch, it will take a little bit of time for it to propagate onto valve's servers, etc -- Let me know if that helped

**Comment by ash47** [comment]
Ok, issue was apparently thirst -- so, disabling it for now :)

**Comment by wwa143** [comment]
Thank you very much for fixing it so quick :D i love playing legendsofdota because it feels like a more awesome mode than ability draft ^_^ .

**Comment by ash47** [comment]
First step is knowing that there is a problem ;)
