### ISSUE TITLE
Aftershock and return crashes the game

### ISSUE THREAD

**Issue by XAgent1990** [ash47/LegendsOfDota#145]
nothing more to say about that

**Comment by ash47** [comment]
0/10 can not reproduce -- Can you verify this wasn't fixed by Valve?

**Comment by ash47** [comment]
This issue will remain closed unless you can reproduce.

**Comment by XAgent1990** [comment]
It was fixed long ago, I don't know if it was fixed by you or Valve, but it is. I posted this 5 months ago

**Comment by XAgent1990** [comment]
It was fixed long ago, I don't know if it was fixed by you or Valve, but it is. I posted this 5 months ago


________________________________
Von: Ashley Schmid <notifications@github.com>
Gesendet: Montag, 25. Januar 2016 15:41
An: ash47/LegendsOfDota
Cc: XAgent1990
Betreff: Re: [LegendsOfDota] Aftershock and return crashes the game (#145)


This issue will remain closed unless you can reproduce.

-
