### ISSUE TITLE
[Request] Join into a lobby with specific mode.

### ISSUE THREAD

**Issue by TheTerorrist** [ash47/LegendsOfDota#146]
I want to ask is it possible to make a button to choose which mode i want to play. Cause there are different modes like all pick, single draft, mirror draft, can it be made like Epic Boss Fight, and choose which mode i want to play before join the lobby. It will be very useful, and helpful for players who want to play a specific mode, like mirror draft. It will reduce the abbandoned games.  Hope you understand me, and i'm sorry my english is not a high level. Thanks!

**Comment by ash47** [comment]
I've thought about that before, I'll consider it again when the player base
increases

**Comment by TheTerorrist** [comment]
ty, cant wait :)

**Comment by Veroalla** [comment]
Please add lod_survival too :smiley: ! (Without trees this time)

**Comment by ash47** [comment]
Lod survival is so dumb, it was just something I wanted to play one weekend
so I directly ported the code from d2ware

**Comment by ash47** [comment]
This needs to be implemented before the next update rolls out, I have added a higher priority issue to track this -- will close this issue since this is now a duplicate.
