### ISSUE TITLE
Neutral Abilities - CANT be switched ON/OFF 

### ISSUE THREAD

**Issue by bazenekdota** [ash47/LegendsOfDota#147]
Hi Legends of Dota developers and players

TITLE is pretty self explinatory. 

When one create lobby server and select **Allow Neutral Abilities: No**

  Neutral Abilities CAN STILL be picked !!

 (most alarmingly Spell Immunity, Back Door Protection - these two alone make it impossible play without +2 bans)

PLEASE for quick fix, TY

P.S.: Could you please add cooldown on Lifestealers Consume ? That ability is really unfortunate since the cooldown is implied by the ultimate, but since you can pick it without the ultimate, it leads to no cooldown spam. It has Cast Time: 0+0.

**Comment by ash47** [comment]
Cool, dearly noted, will attempt to rectify this at some stage, leaving it open until I do ;)

**Comment by ash47** [comment]
Are you sure you didn't have OP skills on? Cause, I just tried and they were disabled?

**Comment by ash47** [comment]
This has been fixed in the new UI. It will roll out when the new UI is ready.
