### ISSUE TITLE
Rupture + Sticky Napalm

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#160]
Crazy tick damages with sticky napalm:
Rupture: Fast 0 damage ticks standing still.
Torrent: 10 ticks
Spirit Siphon: 20 ticks in 5 secs.

I'm not sure if I missed something, but there is a list of damage over time spells: [http://dota2.gamepedia.com/Damage_Over_Time](url)

**Comment by TheRisen41** [comment]
Pls also add sticky napalm + spirit siphon and sticky napalm + lifedrain to the troll combos. Just like rupture they have a 0.25 sec intervall.

**Comment by ash47** [comment]
note: this wont roll out until the next update rolls out.
