### ISSUE TITLE
Another aftershock permastun glitch

### ISSUE THREAD

**Issue by rawinza555** [ash47/LegendsOfDota#162]
apparently, aftershock + magic wand also cause this. Not sure how and why it happens but that's what I saw last game

**Comment by ash47** [comment]
Magic wand as an ability? All item abilities will be removed soon.

**Comment by rawinza555** [comment]
I know it's kinda hard to go over every single skills in the game. but I do think just disable any ability that can't be used by pressing a key would be find

**Comment by ash47** [comment]
This will be fixed when the new UI rolls out.
