### ISSUE TITLE
StatCollection's panorama never uploaded to workshop

### ISSUE THREAD

**Issue by SinZ163** [ash47/LegendsOfDota#163]
if you open up the vpk for LegendsOfDota, the custom_ui_manifest.vxml_c never references it, and statcollection.vxml_c is not present either. (nor is statcollection.vjs_c)

**Comment by ash47** [comment]
Ya, I know, I never pushed that out

**Comment by ash47** [comment]
Basically I've gone past the point where I can push updates, the branch is too messy, I need to complete the recode basically

**Comment by ash47** [comment]
This will be fixed when the new UI rolls out.
