### ISSUE TITLE
Add Multipliers to Result Message

### ISSUE THREAD

**Issue by TheRisen41** [ash47/LegendsOfDota#164]
Please add the different multipliers(tTower, heroes, creeps,etc.) to the result message when Picking/Banning starts. Sometimes you get surprised by towers beeing x5 or creeps x20.

**Comment by ash47** [comment]
These are stupid options, they are being removed completely in the near
future

**Comment by TheRisen41** [comment]
yeah i agree probably the best thing to do

**Comment by ash47** [comment]
These options have been removed in the new UI.
