### ISSUE TITLE
Remove Single Draft

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#166]
First I'd like to say, MIRROR DRAFT IS AMAZING. kudos to ash!

The single draft option has the HIGHEST ragequit ratio of all game modes.
It's so unfair that you have to rely on pure luck on what you get. It's a milder version of random omg of other modes, but more unbalanced.

My opinion is that Mirror Draft should be the only other option for limited drafting.
I'd rather play normal Ability Draft than single draft.

**Comment by Jexah** [comment]
Single Draft is pretty bad, and as it stands it is bugged by design.

@ash47 Perhaps we should consider disabling it until we decide how we would like it to work. More options is great but I share the same concerns as Veroalla.

**Comment by ash47** [comment]
@Jexah how should we implement it in reborn?

**Comment by Jexah** [comment]
@ash47 I'll have a long think and we can have a discussion about it, but for now I think Veroalla has the right idea with disabling it until we figure it out.

**Comment by ash47** [comment]
Cool, how about mirror draft? Or maybe a system where every player gets the
same set of n heroes, then decides which set to pick skills from?

The point is meant to be that there is a limited hero pool though, and also
that people are meant to all get different builds

**Comment by ash47** [comment]
I think the most balanced you could do is something like captains mode

**Comment by rawinza555** [comment]
Or bring something back from Dota 1 Single draft since sd is the most common mode back in DOTA1 LOD like adjustable skills pool (how many heroes can be shown) As I remember we did 50 heroes to pick back in the day. 

-sdd5s6

**Comment by Veroalla** [comment]
ash and rawinza is on the right track I think...
On a similar note... Global Unique spells serves no purpose and makes people quit. Team Unique spells is fair enough. Unless you want poofing + quill spray + fury swipes team ganks T.T

**Comment by Jexah** [comment]
Global Unique is for drafting purposes. In an environment where you have two premade teams of 5, global unique makes sense.

**Comment by Veroalla** [comment]
Team Unique is also for drafting purposes. It's enough to prevent "op combos" like fury swipes that stack additively.
Please enlighten me why global unique makes more sense at all and why. Do you mean the game is all about fastest picker?

**Comment by Jexah** [comment]
It is functionality that was built in, in preparation for competitive drafting. If you have real drafting, and you have two premade teams of 5, then global unique skills is the way to go. 

If you don't understand this, that's fine

**Comment by ash47** [comment]
Single draft has been removed in favour of mirror draft, mirror draft will be implemented hopefully when i get up in the morning <3
