### ISSUE TITLE
Splitshot + Juxtapose

### ISSUE THREAD

**Issue by TheRisen41** [ash47/LegendsOfDota#172]
Juxtapose triggers on every single splitshot traget. Also every illusion then has splitshot which allowes you to have max illusions very rapidly. Please fix this.

**Comment by ash47** [comment]
That's pretty cool, not sure how I would fix that

**Comment by TheRisen41** [comment]
then make it a troll combo cuz it is pretty ridiculous

**Comment by ash47** [comment]
@jexah

**Comment by Jexah** [comment]
I don't find it more powerful than other builds. Get countered pretty hard by Splash, Cleave, SoF, Tidebringer, etc. Also any caster that can get the jump first will trash them.

**Comment by TheRisen41** [comment]
True maybe its not that powerful but it is not supposed to work that way or is it?

**Comment by Jexah** [comment]
It has worked that way for years.

**Comment by TheRisen41** [comment]
Cool i never noticed ^^ then you can close this
