### ISSUE TITLE
Checkboxes instead of Dropdown menu

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#175]
Using checkboxes in the settings picking menu. I think it looks too advanced.
Just an improvement, an appreciated one. If you make a checkbox for each option, the menu will not look so empty and it's easier to see every possible option at a glance.

**Comment by ash47** [comment]
That doesn't really make any sense at all, How do you have a checkbox for gamemode? Maybe you meant a radio button?

**Comment by ash47** [comment]
This has been implemented for options that only have a Yes / No value -- if this is not what you meant, feel free to reopen the issue.
