### ISSUE TITLE
[Suggestion] Choose Attributes for Heroes

### ISSUE THREAD

**Issue by TheRisen41** [ash47/LegendsOfDota#177]
Is it possible that you can add something to make players choose the attributes for their heroes?
I think this would add a lot more diversity to the hero picks cause currently many people are picking the same heros for certain types of bulds (Mirana, Jug, Pugna, Cent).
I could imagine somthing like a skillsystem used in some rpgs: You have a strarting budget of attribute points which you can spend on the 3 attributes(AGI, INT, STR). Also it would be cool to choose from presets like: Balanced(Default), Physical Damge Carry, Caster, Tank, etc.
I know this might be a lot of effort to do but whith such a system every one can pick their favorite hero with any build which would be relly cool.

**Comment by Crainedotexe** [comment]
Read some of the commits, i read it there(so probably next update).

**Comment by Veroalla** [comment]
Why can't there be attribute items that you consume for permanent stats?
I don't like being limited to 6 slot in items. It's super hard to try to counter 5 players in LOD, let alone 2 :(
Unless your build is lucky end-game. If not, you can compensate with stat purchase. but this is after everyone is 6 slotted, will probably lead to a stalemate?

**Comment by ash47** [comment]
It's possible to choose the primary attribute of a hero, eg, you can make a
silencer that is str based

**Comment by ash47** [comment]
The most I am willing to go at this stage is choosing your primary attribute, after that, it becomes the "why even pick a hero at all?"
