### ISSUE TITLE
Improve banning interface

### ISSUE THREAD

**Issue by ash47** [ash47/LegendsOfDota#189]

**Comment by omeger** [comment]
Hello ASH47, i try contact with you. 
Hava an e-mail adress or skype, or simillar?
I want talk with you in private.

Thanks :)

Adam

**Comment by ash47** [comment]
I have no internet.

**Comment by ash47** [comment]
Talk about what?

**Comment by ash47** [comment]
@omeger

**Comment by omeger** [comment]
talk about omegle. 
i can pay much if you cant help.

**Comment by omeger** [comment]
*can

**Comment by omeger** [comment]
@ash47
