### ISSUE TITLE
"you are the host"

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#199]
You're the host is displayed to everyone.
An easy fix is to change to text to "When you are the host, you can pick... yada yada yada..."

May I ask how one can get banned for trolling ppl with settings?

**Comment by Jexah** [comment]
That's also a super lazy fix. This issue is known and if it's not already fixed in the most recent update, it will be fixed very shortly -- properly.

**Comment by ash47** [comment]
This was fixed already before you posted the issue

**Comment by Veroalla** [comment]
my bad

**Comment by ash47** [comment]
Should test my fix
