### ISSUE TITLE
Program crash during skill select [Linux]

### ISSUE THREAD

**Issue by rudmint** [ash47/LegendsOfDota#200]
After the major update and change to skill select interface, my game crashes every time I open the 'find skill' menu.  My System Log shows the same error each time: 

kernel: [1497178.490686] dota2[23540]: segfault at 7fff00000048 ip 00007fdffcc2acb1 sp 00007fffa37331e0 error 4 in libpanorama.so[7fdffc9c1000+519000]

If I wait until hero/skill select is over, I can reconnect and continue play.  If I attempt to connect before the hero/skill select has finished, the game immediately crashes.  I have tried verifying the integrity of the game cache with no change.

Any ideas if this is specific to me or is it a Linux related issue?

**Comment by ash47** [comment]
I'll push it to valve, see what they say about it

**Comment by ash47** [comment]
http://dev.dota2.com/showthread.php?t=192895

**Comment by ash47** [comment]
@rudmint Can you help out?

https://github.com/ValveSoftware/Dota-2/issues/791#issuecomment-197893781

**Comment by rudmint** [comment]
Sorry, just saw this.  I also noticed you replied with another person's specs, did you still need mine?

**Comment by ash47** [comment]
Might as well if you have a crash dump, just leave it there with valve,
could be a sperate crash

**Comment by rudmint** [comment]
OK, I posted it.

**Comment by ash47** [comment]
I see that, I get an email every time someone replies to any lod issues, or
any issues I've commented in :)

**Comment by ash47** [comment]
@rudmint is this fixed?

**Comment by Veroalla** [comment]
I had the same issue before. Rest easy in the knowledge that it's fixed now :)
