### ISSUE TITLE
Improvements: Start lvl 5 option, modification to standard LOD settings?

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#202]
I didn't see the option for start lvl 5 or 250 start gold for normal all_pick LOD. 
It's a good way to boost the game speed and not bore everyone to death *(WE WANT TO TRY OUR COMBOS ASAP, BECAUSE WE ARE SO HYPED!!)*

Start lvl 5 option in all_pick map **pros & cons**:
+Gives all form of builds a good start, whether support or hard carry. Evens out the builds imho.
+Much better than start lvl 6. it gets way too chaotic at start runes with ultimates. lvl 5 gives time to identify enemy skill builds.
+Considering you can easily get destroyed in a lane at lvl 1 if enemy got a super strong harass + ranged hero. you will have a better chance if both start at lvl 5.
+Reduces laning period and speeds up the game

-Start lvl 5 makes it easier to snowball and go all mid and end the game
-Because respawn time is so long

Also, please let host select universal shop for all_pick games. It's a pain in the ass to keep track of all enemy spells AND your courier. (or bring back the free flying courier! :dancers: )

**Comment by Jexah** [comment]
This will either be a separate map, like easy_mode, or will retain its base in custom. Either way, this will not get put into the standard all_pick map.

**Comment by ash47** [comment]
Added a all_pick_fast map -- This will do the following:

```
                -- Fast All Pick Mode
                if optionValue == 2 then
                    -- Set gamemode to all pick
                    self:setOption('lodOptionCommonGamemode', 1, true)

                    -- Set respawn to 10%
                    self:setOption('lodOptionGameSpeedRespawnTime', 10, true)

                    -- Starting level is lvl 6
                    self:setOption('lodOptionGameSpeedStartingLevel', 6, true)

                    -- Turn easy mode on
                    self:setOption('lodOptionCrazyEasymode', 1, true)

                    -- Start with 2500 bonus gold
                    self:setOption('lodOptionGameSpeedStartingGold', 2500, true)
                end
```

**Comment by ash47** [comment]
This has now rolled out, pretty sure that is what you wanted.
