### ISSUE TITLE
Report some combo

### ISSUE THREAD

**Issue by testiclesbomber** [ash47/LegendsOfDota#203]
![20160317021952_1](https://cloud.githubusercontent.com/assets/17896120/13838005/d4af5bde-ebe6-11e5-8d69-dc70947c1909.jpg)
I've tried this build many times. this combo can easily FF the game without fighting with any hero.

take aim + web make ranged hero untouchable.(with 1030 attack range)

Over power with ranged hero will cause the buff of overpower stay longer. when the proj does't arrive the enemy.(normally occured with 'take aim')

**Comment by ash47** [comment]
@Jexah counter this

**Comment by Jexah** [comment]
Well, every game I play in has Grow and Spin Web banned so I don't really have to.

That Overpower interaction is known and not a bug.

**Comment by testiclesbomber** [comment]
Actually you dont really really need Grow, Spin Web and Take aim is enough ,Only thing I need increase DPS.
like use Chemical Rage or God's Strength to replace Grow.

**Comment by Jexah** [comment]
Yeah, ranged Spin Web is pain. I also like to ban chem rage.

**Comment by ash47** [comment]
Ultimately, just ban spin web if you think it's OP, it will be much easier to get a banning phase soon.
