### ISSUE TITLE
Berserkers Rage doesnt give the in tooltip written values

### ISSUE THREAD

**Issue by Crainedotexe** [ash47/LegendsOfDota#205]

**Comment by Crainedotexe** [comment]
![20160319121419_1 2](https://cloud.githubusercontent.com/assets/8344479/13898634/d8b6d930-edd7-11e5-86f3-d201f0d9cede.jpg)
![20160319121421_1 2](https://cloud.githubusercontent.com/assets/8344479/13898633/d8b1e8a8-edd7-11e5-9339-888aef025cfe.jpg)
![20160319121646_1 2](https://cloud.githubusercontent.com/assets/8344479/13898632/d8b1f730-edd7-11e5-9834-9af36e7dcf11.jpg)

**Comment by Jexah** [comment]
I don't understand the issue. In the first two screenshots you've put a border around move speed, and in the third screenshot you put a border around bash damage...?

**Comment by Crainedotexe** [comment]
Oh wow i should learn to read...

**Comment by Jexah** [comment]
Haha, please close Ash.
