### ISSUE TITLE
Respawn Timers not functioning

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#206]
Reduce respawn doesn't seem to work. Troubleshooting by dieing at lvl 25:

50% reduction results in 100 second respawn time.
10% reduction results in 100 second respawn time.
0% reduction results in 100 second respawn time.

The other fixed respawn timers seem to work though. **Except for meepo**, only 1 clone gets the fixed respawn time.

**Comment by puppybull** [comment]
Note: 
Fixed respawn timers mess up the aegis respawn time and suicide respawn time, I'm unsure about scythe but I assume it also affects that

**Comment by ash47** [comment]
Have you tested aegis recently, as I specifically fixed that for this
update, I think the 50% etc might have broken due to stat collection

**Comment by ash47** [comment]
0.1 and 0.5 were being rounded to 0, so, ez fix :)

**Comment by puppybull** [comment]
Nice, thank you!

**Comment by ash47** [comment]
It will roll out when I stop being lazy

**Comment by ash47** [comment]
Tried yo upload this, keeps failing, need to wait for valve to fix their workshop again, sigh
