### ISSUE TITLE
Slark's ultimate

### ISSUE THREAD

**Issue by puppybull** [ash47/LegendsOfDota#209]
If you have it skilled, fighting Roshan doesn't disable Shadow Dance regen.

Also, Shadow Dance passive icon can be seen without levelling it up
The regen and movement speed effects are muted, but you can still see the icon (and see it disappear

**Comment by ash47** [comment]
I don't really care about the icon as it has no actual effect and is only cosmetic, didn't know about the roshan / creep thing.

**Comment by ash47** [comment]
This was fixed when I fixed the slark modifier icon :)
