### ISSUE TITLE
Suggestion: Void model being immune to chronosphere

### ISSUE THREAD

**Issue by puppybull** [ash47/LegendsOfDota#210]
Ban selecting void as a hero by default is the only thing I can think of that wouldnt require extensive work (like making it so anyone who has chronosphere is immune to chronosphere or something insane like that)
Is that doable, adding void as a hero to the "LoD banlist" or whatever?

**Comment by Veroalla** [comment]
or make him not pickable together with chronosphere? lol joking...
The main issue is if your own team all pick void and nature's teleportation and kill anything together inside chrono.

Thank god this is not in the suggested builds hahaha. So I don't see a reason to put it in the LoD banlist, that's my opinion. Feel free to argue your point.

**Comment by Jexah** [comment]
That is what makes Faceless Void viable. Each hero has their own quirks. Please close Ash.

**Comment by ash47** [comment]
I agree with Jexah, every hero has their own perks, for example, alch can gift scepters, I really like this and it helps when considering which hero to select.

I imagine it's very easy to fix this, same thing as silencer, @jexah do you think I should tie walking in a chrono to void, or to the ability itself? Could be very interesting if it's moved (or added) to the ability itself.

**Comment by Jexah** [comment]
I think it should be tied with the hero. The only reason silencer was changed was because his passive was extremely strong.

**Comment by ash47** [comment]
Good idea, but I'll stick with what Jexah said and leave it tied to the hero for now.
