### ISSUE TITLE
Bug report INFINITY heroes

### ISSUE THREAD

**Issue by testiclesbomber** [ash47/LegendsOfDota#212]
Precondition: 
LOD banlist OFF  
respawn time 10%/30%/1sec/10sec
choose hero: Meepo
Ability: Tempest double

![20160325032319_1](https://cloud.githubusercontent.com/assets/17896120/14040118/42837204-f23a-11e5-9add-263e4ca2fc32.jpg)
![20160325032405_1](https://cloud.githubusercontent.com/assets/17896120/14040120/42847b72-f23a-11e5-8065-abda7e71d33f.jpg)
![20160325032803_1](https://cloud.githubusercontent.com/assets/17896120/14040119/42846a7e-f23a-11e5-8242-1c22817931c4.jpg)
![20160325032143_1](https://cloud.githubusercontent.com/assets/17896120/14040121/42851a14-f23a-11e5-9bc7-4edf52e5ffcd.jpg)
![20160325032151_1](https://cloud.githubusercontent.com/assets/17896120/14040122/42868ef8-f23a-11e5-984c-807bdce09558.jpg)
![20160325032222_1](https://cloud.githubusercontent.com/assets/17896120/14040123/42879186-f23a-11e5-93e0-d4253dc3ba6a.jpg)
![20160325032255_1](https://cloud.githubusercontent.com/assets/17896120/14040124/428925c8-f23a-11e5-97c0-99dbe3681d7d.jpg)

**Comment by ash47** [comment]
So you're saying that the tempest double can cast tempest double?

**Comment by testiclesbomber** [comment]
No, I mean when tempest double is dead. he will respawn and became a true hero.(interaction between meepo's hero ( respawn time) and fast respawn mode).

**Comment by ash47** [comment]
That's actually a really cool glitch, and I think I know why :)
