### ISSUE TITLE
Bugs with bots

### ISSUE THREAD

**Issue by XAgent1990** [ash47/LegendsOfDota#217]
- It seems like some summons of bots are controlable by players as well as some heroes from bots (We had a game where I was able to control the enemy Dazzle into my frountain and waste all his items as well as controling all the summons this game) 
- In any game that I play with one mate we have on one team the last bot being idle EDIT: This didn't happen yet when i was playing alone
- <s>I yet haven't had a game with tidehunter working</s>

**Comment by ash47** [comment]
Arg, I can't reliably make the bots controllable by a player in order to work out why this happens :(

**Comment by Puddinfox98** [comment]
I don't know if this is the same problem as the Tidehunter, but for all the games I've played with a bot razor it just sits in the fountain and buys items. It doesn't matter if it is friendly or enemy razor.

**Comment by ash47** [comment]
Ya, I banned razor already

**Comment by Puddinfox98** [comment]
Ok, just making sure that was the problem

**Comment by Veroalla** [comment]
Once Chaos Knight bot bought the courier and kept it in his inventory. I swear he was trolling us

**Comment by ash47** [comment]
I think I have fixed the issue with bots being controllable. Need someone to confirm?

**Comment by ash47** [comment]
Can anyone confirm if this is still the case?

**Comment by XAgent1990** [comment]
The only thing i once had was that a bot still stayed in base with the courier right until second 0 when the game started, then he moved and worked properly again

**Comment by ash47** [comment]
This APPEARS to be fixed, the only real issue is bots sometimes wait until 0 seconds to start moving, but, that's a meh
