### ISSUE TITLE
Respawn time

### ISSUE THREAD

**Issue by puppybull** [ash47/LegendsOfDota#218]
It was fixed a while ago, but I think in one of the recent updates it is back to Aegis taking forever to respawn / Scythe doesn't add time etc

Edit: I use 50% spawn

**Comment by ash47** [comment]
I'll take a look again, SIGH

**Comment by ash47** [comment]
#213 check meepo respawn timer too

**Comment by ash47** [comment]
Unable to reproduce a broken aegis / broken WK ulty, don't care about Scthe, and will look into meepo ulty soon.

**Comment by ash47** [comment]
This should now all be solved :)

**Comment by puppybull** [comment]
Aegis was solved, but now it seems to be broken again

**Comment by ash47** [comment]
I need exact instructions of how to reproduce.

**Comment by darklordabc** [comment]
I'm not sure, but my understanding was aegis respawn will be fucked up, IF there is a FIXED respawn time, but not if there is a percentage respawn time. I.e. if you set 20 second fixed respawn time, aegis respawn will take 20 seconds.
