### ISSUE TITLE
Some comments from cn players

### ISSUE THREAD

**Issue by ethereal64** [ash47/LegendsOfDota#220]
I introduce lod to them in chinese version, and heres what i heard most about the new changes. First of all, the biggest complain is about the change to after shock and multicast. The main argue is the change destroyed these skills. Is it possible to list the original skills as op skills and only available in custom mode? Secondly, some is requesting search skills using chinese, is it possible? pls tell me if chinese support is needed.

**Comment by ash47** [comment]
The skill search should support chinese searching -- If you can confirm it doesn't work, I can look into it.

I can add back the OP version of aftershock via an option

**Comment by ash47** [comment]
Just added back the old variant, it will be back in the workshop version when I update it.

**Comment by Veroalla** [comment]
I noticed troll combos are allowed by default in all_pick and all_pick_fast too. Is this intended?

**Comment by ash47** [comment]
Oh, this is not intended :O

**Comment by Veroalla** [comment]
My bad ash, I could pick bear return. So I thought there was something fishy. but mostly troll combos are disabled.

**Comment by ash47** [comment]
@ethereal64 I have implemented region specific skill seaching which should allow chinese players to search using chinese skill and hero names :) Just need to wait for me to roll out the patch :)

I think I have addressed everything else you have raised, so, if you have no objections, I consider this issue closed :)

**Comment by ash47** [comment]
Just rolled out the patch that lets you search using chinese characters, can you let me know if it works @ethereal64 ?

**Comment by ash47** [comment]
No response, I will assume this is fixed.
