### ISSUE TITLE
Option voting

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#222]
When you vote for 4 slots the game picks 6 slots and vice versa wtf xD
and picking no bans, will enable the bans!!

**Comment by ash47** [comment]
That's weird, will take a look

**Comment by ash47** [comment]
Are you playing with other people, or did you notice this solo?

**Comment by Veroalla** [comment]
I was playing with other people.
Because 6 slot is so popular the games end up 4 slot. and everyone wants bans, they end up with no ban games.
I should test it under more controlled environment... BUT I was the last deciding vote between 4 or 6 slot, and I could easily see how it behaved when I switched vote between the two.

**Comment by Veroalla** [comment]
Unrelated note. Picking 4 bans gives you 5 bans. in custom

**Comment by ash47** [comment]
I can't confirm this, the logic says this should not be the case, can you base this off something that isn't a gut feeling?

I will remove the code that counts votes soon.

**Comment by ash47** [comment]
Is there any updates on this @Veroalla ? I have been unable to reproduce anything like this, note that people can change their vote during the voting phase as many times  as they want.

**Comment by ash47** [comment]
This has been fixed now, found the bug <3
