### ISSUE TITLE
Ghost Walk Lv 4 actually decrease your move speed LOL

### ISSUE THREAD

**Issue by testiclesbomber** [ash47/LegendsOfDota#223]
The Ghost Walk will decrease ur move speed at lv 4 by -30% not 30%

**Comment by ash47** [comment]
This is actually a weird interaction with the scepter. It seems that a scepter makes all of invokers abilities reset to level 1.

Looking into this :/

**Comment by ash47** [comment]
A decrease of a negative number will result in an increase in movement
speed, so, -1 x -1 = 1

I understand the issue, it's caused due to the way the scepter interacts
with the abilities.

**Comment by ash47** [comment]
still in the process of trying to find a work around :/

**Comment by ash47** [comment]
This is a duplicate of https://github.com/ash47/LegendsOfDota/issues/223
