### ISSUE TITLE
Stuck at please wait

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#224]
Does this only happen to me? 1 second it was working fine, the next matches are always blacked out!
The console output: 

> CL:  Sending connect to =[A:1:162377730:6618]
CL:  Received S2C_CHALLENGE [4218638618 auth 3] from =[A:1:162377730:6618]
CL:  Sending C2S_CONNECT [44 protocol 4218638618 auth 3] to =[A:1:162377730:6618]
Switched to backup #1 vie#49 (185.25.182.226:27027) as primary, session 3117bd6b.  Ping = 67+0=67 (front+back=total).  [Previous primary fra#110 (162.254.197.73:27016): Ping = 62+11=73 (front+back=total).]
Selecting fra#110 (162.254.197.73:27016) as backup #1, session 39c798bb.  Ping = 62+11=73 (front+back=total).
CL:  Received S2C_CONNECTION from =[A:1:162377730:6618] [addons:'296590332']
CL:  Connected to '=[A:1:162377730:6618]'
CL:  Suppress INetchannel::Transmit() in loopmode( remoteconnect )
CL:  CLoopModeRemoteConnect::OnClientFrameSimulate switching to "levelload" loopmode with addons:  296590332
SwitchToLoop levelload requested:  id [20] addons [296590332]
Mounting addon '296590332'
ChangeGameUIState: DOTA_GAME_UI_STATE_DASHBOARD -> DOTA_GAME_UI_STATE_LOADING_SCREEN
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( levelload : success )
CL:  Permit INetchannel::Transmit()
CL:  CLoopModeLevelLoad::OnClientFrameSimulate switching to "game" loopmode with addons: 296590332
SwitchToLoop game requested:  id [20] addons [296590332]
CL:  CNetworkGameClient already exists for connection to '=[A:1:162377730:6618]'
CL:  connection to '=[A:1:162377730:6618]' already started
Game: "Dota 2"
Map: "all_pick"
Players: 3 (1 bots) / 64 humans
Build: 7090 (revision 3377640)
Server Number: 2
CL:  CNetworkGameClient::ProcessServerInfo
Initializing script VM...
...done
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_INIT'
CL:  CGameRulesGameSystem::GameInit installed game rules
ReadSteamRemoteStorageFile( bufOut, "voice_ban.dt" ) -> 0.000148 seconds
Loading custom UI:
ERROR: Unknown resource type (txt) for resource "scripts/game_sounds/frostivus.txt"!
File error loading resource header "models/controllers/vr_controller.vmdl_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/effects/fog_world_00.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/effects/fow_clouds_00.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "particles/econ/events/fall_major_2015/compendium_points_fall_ambient_2015_magic.vpcf_c" (Error: ERROR_FILEOPEN)
File error loading resource header "materials/models/heroes/queenofpain/queenofpain_weapon.vtex_c" (Error: ERROR_FILEOPEN)
File error loading resource header "models/heroes/skeleton_king/skeleton_king_deathsim.vmdl_c" (Error: ERROR_FILEOPEN)
CL:  CGameClientConnectPrerequisite connection succeeded
ChangeGameUIState: DOTA_GAME_UI_STATE_LOADING_SCREEN -> DOTA_GAME_UI_DOTA_INGAME
CL:  IGameSystem::LoopActivateAllSystems
HO:  IGameSystem::LoopActivateAllSystems
CSF_Hud_Custom::Init lod
ReadSteamRemoteStorageFile( bufOut, "scripts/control_groups.txt" ) -> 0.000170 seconds
Remote Connect (=[A:1:162377730:6618])
CL:  CNetworkGameClient::OnSwitchLoopModeFinished( game : success )
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
CDOTA_SF_HTML disabled in Source 2
CL:  Receiving uncompressed update from server
CL:  Signon traffic "client":  incoming 257.540 KB [10 pkts], outgoing 19.591 KB [408 pkts]
C:Gamerules: entering state 'DOTA_GAMERULES_STATE_PRE_GAME'
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME
ChangeGameUIState: DOTA_GAME_UI_DOTA_INGAME -> DOTA_GAME_UI_DOTA_INGAME

Verify intgrity of gamecache didn't solve it.

**Comment by Veroalla** [comment]
Re installing LOD fixed it. close?

**Comment by ash47** [comment]
Something is rooted up with the workshop

**Comment by Veroalla** [comment]
It returned again.

**Comment by ash47** [comment]
I have pushed a patch that may help, but I really don't know :/ Need some testing to happen.

**Comment by ash47** [comment]
Just pushed another patch again :/

**Comment by ash47** [comment]
Can people confirm if this is happening ONLY when other people have left before the spawning starts?

**Comment by ash47** [comment]
I have added code that will just literally print to the chat what the issue is -- if you get stuck again, tell me what is posted to chat (if anything) and that will be a huge help in solving this issue.

**Comment by Veroalla** [comment]
Can I still read the chat from console when the screen is black?
Or do I have to wait for someone else in the game to experience this issue?

**Comment by Veroalla** [comment]
Custom mode. 2 guys abandoned during settings. Game still loaded in just fine for everyone.

**Comment by ash47** [comment]
Does that mean it's fixed?

**Comment by Veroalla** [comment]
Yes I think so. The people loading in has increased substantially. Good job I think! :D

But people reconnecting incur a massive lag spike independent on CPU power. Everyone in the game experience it on several occasions. It's not high priority though?

**Comment by ash47** [comment]
I didn't know about this, no idea what could have caused the lag spike, open a seperate issue for it.
