### ISSUE TITLE
Spawning a spirit bear using Arc Warden crashes the game

### ISSUE THREAD

**Issue by ash47** [ash47/LegendsOfDota#230]

**Comment by kingalca** [comment]
Confirmed.

**Comment by ash47** [comment]
Unable to reproduce, need more details @kingalca

**Comment by ash47** [comment]
Can I get some more details on when this happens?

**Comment by testiclesbomber** [comment]
Crused again. I choose Divide We Stand. Templest Double and spirit bear.
Divided we stand and Spirit bear is good 
But Divided we stand Spirit bear and Templest Double will crush the game

**Comment by testiclesbomber** [comment]
more like interact between Divided We Stand and Templest Double

**Comment by testiclesbomber** [comment]
Actually no matter which hero u choose. just Templest Double and Spirit bear.
I tried bloodseeker with Templest Double and Spirit bear and game crushed after the Templest double dead.

**Comment by kingalca** [comment]
Arc Warden Ult + Morphling Ult + Scepter + Summon Bear => Crash.

Crashes like 1000000% of the times tried. Pretty easy and well documented in the Steam Game comment section as well.

**Comment by ash47** [comment]
Just added a fix to the repo that patches this. Just remember it isn't live on the workshop just yet :)
