### ISSUE TITLE
Custom % of Respawn Time.

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#237]
Currently there is only a preset % of respawn time you can choose from. Either 50% or 10%. 50% ends up being too long, but 10% ends up being much too quick (until late late game). Right now the workaround is to set it to a fixed 10 second time, but that quickly becomes much too short as the game enters the late game period. A fix would be to be able to choose a custom %, or add a % in between 50 and 10% (e.g. 25% respawn time).

**Comment by darklordabc** [comment]
This is what ash47 said about this suggestion in steam community (I'm posting to help him remember just in case he has forgotten). :** " could possibly have two bars, so it is x% of your normal spawn + y seconds, so you could set y to be 0 and just use the percentage, or set x to be 0 to just set a number of seconds."**

**Comment by ash47** [comment]
This has been fully implemented. It will roll out in the next update.
