### ISSUE TITLE
Custom Gold Rate

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#238]
Right now the only option to allow a quicker income of gold, is by enabling "easy mode". It would be a nice feature if you could increase the default 1 per second gold to a higher value. 

Personally, I want this because I think it encourages a quicker game and it allows heroes with non-farming abilities a way to get income.

**Comment by ash47** [comment]
This has been implemented.

**Comment by ash47** [comment]
Additionally, I have removed easy mode, and added a modifer (0 - 10) that allows you to set the EXP and Gold rates individually.
