### ISSUE TITLE
Auto Balance or Switch Option, if many players disconnect at start of game.

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#239]
A common problem with hosting LoD, is that there is always at least 1 disconnect from the start of the game. 1 is not a problem, even 2 is not a problem, if it is 1 from each time. But sometimes, 2 or more players will disconnect from the same team, leaving the game 3 vs 5 or 2 vs 4 etc. 

In Warcraft 3 LoD (and original dota) there was a **-switch** command that players could type. Which allowed them to nominate to swap to the opposing team. When players did this command, a vote would be called and a super majority would be required to allow the player to swap teams (to avoid abuse). In LoD Reborn this could be a graphical UI popup. 

This feature was used almost exclusively for balancing the game when it had clearly become unfair because of disconnects. This feature would be very useful for the current LoD Reborn. 

Another similar feature, could be adding auto team switching, if at the start of the game, the teams are unbalanced by more than 1 player. For example, if after selecting skills, 2 players have abandoned, and the lineup is 3 vs 5, the game could automatically switch one random player from the 5 team to the other team. This would save a lot of games, that right now, just have to be bailed on or played at a huge disadvantage to the 3 team.

**Comment by darklordabc** [comment]
![image](https://cloud.githubusercontent.com/assets/16277198/14581002/1bb70b30-0424-11e6-91a0-38ef0fad90a9.png)
It could also be implemented by a right click on a player from the player menu.

**Comment by ash47** [comment]
Not sure if it's possible, i'll see what can be done.

**Comment by ash47** [comment]
Well, I just implemented the swapping part, however, you can't use it yet because there is no GUI. The swapping does work (with bots at least), I just need to make a GUI for it and a voting system, sigh, lots of work :(

**Comment by darklordabc** [comment]
Could you make it command based for the short-term? In warcraft, writing -switch with no number, would show a list of players and their corresponding numbers. typing switch 3 (for example), would attempt to swap with player 3 (usually a disconnected player) and players would have to type -yes or - no

**Comment by darklordabc** [comment]
Pimp my peon has some pretty cool custom interfaces. Could you use something like this. E.g. having a "switch" button instead of a tutorial button, or maybe an extra icon on the score board, or even having the _"i"_ info sidebar slide out, with switch options. 
![image](https://cloud.githubusercontent.com/assets/16277198/15061349/3a78e3ec-1377-11e6-8c4f-542305848a2a.png)

**Comment by ash47** [comment]
Why would you close this issue? It's still WiP, I've been busy managing the other issues / pull requests that have been coming in - I can look at issues and pull requests, or I can code additional functionality, can't do both.
