### ISSUE TITLE
Game hangs on "Setting up Game"

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#240]
I just tried a single draft game, and it never loaded into the game it was stuck permantely on the "setting up game" stage. I tried again, solo, and it still got stuck on the same part. Right now game is unplayable.

**Comment by ash47** [comment]
Was this solo? Does this also happen in mirror draft?

**Comment by XAgent1990** [comment]
No it does not happen for mirror draft, it only gets stuck in single draft

**Comment by ash47** [comment]
Cool, I'll try to reproduce maybe tomorrow if I get time

**Comment by ash47** [comment]
I'll roll out a patch with this when I get some time :)
