### ISSUE TITLE
New Idea: Ability cost points mode.

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#241]
A mode where each player only has say 20 points to spend on abilities. Abilities which are almost always picked, will be the "high-tier" abilities, and they will cost the most points, for example 10 points for chemical rage, or dispersion, or borrowed time. 
And low-tier abilities, which are almost never picked, like some neutral creep abilities, or any of warlocks non-ultimate abilities, etc will cost the least amount of points to buy, like 2 points for Shadow Word.

This mode could be addable to any of the preexisting mode, like all pick, mirror draft or single draft, and it would have the advantage of encouraging players to use uncommon abilities and builds, making for more interesting and memorable games. 
It would also be great if the mod could globally keep track of which abilities are picked, and use that data to automatically make the high-tier, mid tier and lower tier lists, so that the developer does not have to preset any particular abilities, they could be done automatically. If you like this idea, I will make an issue for it.

**Comment by ash47** [comment]
@Jexah Thoughts?

**Comment by Jexah** [comment]
Certainly an interesting idea, but I'd be concerned about the development cost.

**Comment by darklordabc** [comment]
Costs? In terms of time, money??

**Comment by Jexah** [comment]
Time is money? Kappa.

**Comment by Penguinwizzard** [comment]
Writing the feature costs a lot of time, balancing costs a lot of time, it'd be a source of a lot of extra work to handle complaints about balancing, and it'd constantly have to be reworked as the metas change and other bugs get fixed and introduced.

However, there's some interesting stuff in there; if the number of games is high enough, it might be possible to perform statistical analyses to get finer-grained costs than simple ability tiers; you could check the correlation between picking a certain ability (or combination of abilities) and winning/losing the game, and then dynamically balance around that (maybe on a 2-week cycle).

**Comment by darklordabc** [comment]
Who are the developers for this mod? I know Ash is the lead developer, but is Jexah helping too, and is there any others?

**Comment by ash47** [comment]
Just look at the commit log and it tells you exactly who has done what.

**Comment by darklordabc** [comment]
You are the only person in the commit log ...

**Comment by ash47** [comment]
There's a handful of other contributes, they haven't made many commits, the
majority of the code base is me. I've maintained it for almost 2.5 years.

**Comment by ash47** [comment]
Probably not going to happen.

**Comment by darklordabc** [comment]
What about adding statistics on which abilities are picked? If that is implmented I could try doing this mode, or getting my programmer friend to give it a try.

**Comment by ash47** [comment]
https://github.com/ash47/LegendsOfDota/issues/281

**Comment by darklordabc** [comment]
So I had free time and I was just playing around with the concept so much and this is what I thought it could look like. 
![image](https://cloud.githubusercontent.com/assets/16277198/15999544/d0fff866-3189-11e6-9ff2-50eb4e1116b9.png)
![image](https://cloud.githubusercontent.com/assets/16277198/15999554/e5f30ff6-3189-11e6-9ca8-71140e866246.png)

**Comment by darklordabc** [comment]
Alternate way of showing the values of spells. What I like about this display method is that it doesn't have the change the arrangements of skills, just has to add a tiny colored line to show what tier they belong too, dont have to mess with the rest of the GUI. 
![image](https://cloud.githubusercontent.com/assets/16277198/16000109/7b0b870a-318d-11e6-970d-87d8c51b7049.png)
