### ISSUE TITLE
Game mode completely broken

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#243]
I've just played in around 6 games, in different continents, and all of them the gamemode is entirely broken. The GUI does not load, the game enters like a normal game, players go into game with no abilities. 
![image](https://cloud.githubusercontent.com/assets/16277198/14610835/cac64348-05d2-11e6-8413-773b4c58bc8d.png)

**Comment by ash47** [comment]
Woops

**Comment by darklordabc** [comment]
Working now

**Comment by ash47** [comment]
I think this has been fixed, can someone confirm? The update seemed to be corrupted basically.

**Comment by darklordabc** [comment]
Yeah its working.
