### ISSUE TITLE
Neutral Abilities Problems - Some Are Upgradeable, but seem to give no benefit

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#244]
There are a few neutral abilities, which can be leveled up, but in the description at least, seems to give no benefit. Please either make these abilities only have 1 level, like most other neutral abilities, or update the descriptions to reflect what improvement leveling up these abilities do. 
These are: 
Poison - The Second one. The first one is good, but the second has no benefit for upgrading.
Fireball 
Entangling Claws
All of Rosh abilities (Bash, Spell Block and Slam)
![image](https://cloud.githubusercontent.com/assets/16277198/14709258/147c3c08-0813-11e6-9a56-049f648c4c82.png)

P.S:
Another problem is pitlord abilities. They have no icons and are difficult to see. I didnt even realize they were there after playing many games. Please add some icons. There are icons for abilities on [this page ](http://dota2.gamepedia.com/Abyssal_Underlord).
![image](https://cloud.githubusercontent.com/assets/16277198/14709252/0b4ae30a-0813-11e6-8c57-7b48d349d3f2.png)

P.S.S: 
I love the stone form ability. But upgrading it gives very little benefit (tiny bit more damage on landing, tiny bit more stun, and more regen. It would be cool if this would made into a 1 point ability, or if you make upgrading it a little bit better (its already a fantastic ability).
![image](https://cloud.githubusercontent.com/assets/16277198/14709312/5271309a-0813-11e6-98f6-b5cce0c8084d.png)

**Comment by TheRisen41** [comment]
I think stone form should not be buffed. At level 1 it is much better than cold embrace only disadvantage is that you can only cast it on your self. If it would be changed to a 1 point ability with for example the values of the level 2 ability as it is now you could heal yourself for 549,6 hp for free every 26 seconds at level 1 which is a bit too strong. I think it just needs a 4 ability points scaling.
For example: 20/45/70/95 Hp per second

**Comment by darklordabc** [comment]
Issue has been fixed
