### ISSUE TITLE
Stealth Nerf to Tempest Double? Or broken?

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#247]
Tempest Double does not work as it used too. Its meant to refresh the cooldown on all abilties and items, now it does not do that. The double seems to instead have its own cooldown, and they dont get refreshed when the ability is used. Even a midas, which is core for Arc Warden, does not refresh. 

Also, the doubles don't get divine rapiers, which is also a core strat for arc warden. 

Too much of a nerf in my opinion. It would be good if tempest double did not refresh ULTIMATE cooldowns, but still refresh item cool downs (besides refresher orb).

If you are going to keep these heavy nerfs to tempest double, you should at least say what the nerfs are in the ability description.

**Comment by Jexah** [comment]
Just because something is in the game, doesn't make it a feature. 

I'm pretty sure all of this is one bug.

**Comment by Jexah** [comment]
Oh, my bad. Turns out this was a nerf introduced by Valve in the latest patch.

http://puu.sh/owdaa/ec798ce669.jpg

**Comment by ash47** [comment]
Valve changed the ability, not much I can do. If they think it's more balanced, I am all for that change.

**Comment by darklordabc** [comment]
Okay, thats all good. I didnt know about the update, I'll close this issue.
