### ISSUE TITLE
Suggestion: Give players 2-5 bans each, not 10.

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#251]
I notice that in the all pick map, people usually always vote to skip ban phase, which is a shame, because there is only a handful of abilities that are ALWAYS used, like duel, essence shift, alchs ultimate etc.

Part of the reason for this, is because the ban phase is set to a ridiculous amount of bans. 10 ability bans and 2 hero bans? Putting aside the fact that nobody even bothers to ban heroes ever, when players play custom games, they never give 10 bans, the most they would give is 5. 10 bans each, is a 100 abilities banned in a normal AP game. I think this high ban count is why people avoid the banning phase altogether. I suggest you lower it to a more normal number, like 1, 2, 3 or 4 bans each.

**Comment by Jexah** [comment]
What you describe is different to your suggestion.

You're describing an issue with how most people like to play the game; with no bans. Your solution doesn't fix this, people will still vote to ban nothing, because the majority of players want to play broken stuff.

A potential fix to the issue you've described would be to force a small number of bans, and be able to vote for more, but this is a double edged blade, as you begin to alienate the majority user-base.

Although with the most recent patch to Dota, Ranked All-Pick now allows each player to ban a hero. Maybe we can use this as an excuse to put a small number of personal skill bans in?

**Comment by ash47** [comment]
Additionally, you are only looking at the games you play, not at the whole
picture, after no skill bans, 10 is by far the most common number of bans.
Additionally, more people select to ban 25 skills than 5.

At the end of the day, all pick is for someone who wants a quick game, if
you want specific rules, play the map that corresponds to the rule set you
want.

**Comment by darklordabc** [comment]
//This suggests that people either like bans or they don't, regardless of the number.//
That's like saying people like tea in their sugar, regardless of amount, and then being surprised when people complain about you putting 10 teaspoons of sugar in their tea. 

I understand that a majority of players don't want bans, but the significant portion of people who do like bans, almost never choose 10 ability bans, and I have played in a lot of games with bans. So why is it set at 10, when that is not what anybody wants? I remember, when I made a game with all things enabled, and gave 10 bans to each player, half the players disconnected in protest, and I had to abandon the game. 

//Additionally, you are only looking at the games you play, not at the whole
picture, after no skill bans, 10 is by far the most common number of bans.
Additionally, more people select to ban 25 skills than 5.//
I have played in many many games of LoD, and have never seen 25 bans. And 10 bans is extremely rare and usually results in players abandoning. Do you have data on this, because I'm sure if you looked at recent custom games that allowed player bans, the vast majority of them will give the players less than 10 bans.

I'm just not understanding the rationale for 10 bans per player. People who hate bans, hate it even more, and people who do like bans, would never personally set it to 10, especially since in the all pick map, OP and Lod bans are already activated. 10 would be more justified if LoD and Op abilities were enabled (but you can't do that because then too many games would get ruined).

**Comment by Jexah** [comment]
No, it's nothing like that. That is a terrible analogy. You've missed the point completely. People either playing the most broken shit, or they like to balance things out. The difference between 0 and 3 bans is greater than the difference between 3 and 10 in terms of balance.

In regards to your third paragraph, I can tell you I've played over 5k games of LoD and the majority of them have been 20 bans.

Yes, Ash has raw data on this, he is not just talking out of his ass, and the empirical evidence I provide in terms of broad scope is second to none.

"people who do like bans, would never personally set it to 10"

*cough*

**Comment by ash47** [comment]
http://i.imgur.com/Xh3Igc7.png

Enough said

**Comment by darklordabc** [comment]
Not really ash47, is that data for the custom games where players have specifically set 10 bans? Or does it include data from the all pick games where 10 is fixed?

**Comment by jimmydorry** [comment]
Subscribing to thread.

**Comment by darklordabc** [comment]
//I see that you just want to understand our reasoning, and you can disagree with our decisions, but you can't disagree with the facts we describe. Criticism is healthy, but arguing with what we state as facts is pointless and a waste of time, because we've already done the work.// 
I'll respect the facts. If it turns out that people are _choosing_ 10 bans, and that is what most people who like bans prefer, than I'm fine with it staying 10. But I will be shocked and stunned if people are actually are choosing 10 bans in custom games, because that has been completely not my experience with this game.

**Comment by ash47** [comment]
There is more than one region of players, have you played in every region,
we are in the process of updating the stats for today, will provide more
detailed stats when they have finished processing.

**Comment by Jexah** [comment]
The point is, that the overwhelming majority of players choose zero bans, and 10 bans per player tends to balance the game out well without stunting creativity. Most players who are okay with 5 bans, are okay with 10 bans, but few players who are okay with 0 bans, are okay with 5.

10 bans is enough to remove most of the broken skills, and gives enough room for strategic play around any skills that a team might want to play around, we can't remove 0 bans, and we can't add more options as that would decrease the ratio of players who get what they want.

Frankly I'm surprised (and proud) that there are that many AP games that vote to use bans.

**Comment by darklordabc** [comment]
10 bans per players, is 100 bans. Its overkill. You only need to ban a handful of abilities to force players to think originally. You can basically count the abilities on two hand. Grow, essense shift, impetus, infest, duel, feast, blinks, dispersion, chemical rage and a few others. You ban those like 15 abilities, and you would already have a dramatically different game. You do not need a 100 bans. Especially since the broken abilities are already banned in all_pick_6 map.

But I'll wait for the data that Ash47 is working on. In the meantime, I will take a screenshot of every custom games that has ability bans per player enabled, and I'll report back with an album.

**Comment by jimmydorry** [comment]
Don't both taking images. For every game you record, there would be hundreds of others recorded. The plural of anecdote is not fact.

**Comment by ash47** [comment]
I frequently don't ban any skills even when banning is enabled, I'm sure
there are other players in this bucket, I highly doubt that every player is
using all their bans.

We could potentially even start to track the number of bans people have vs
what they are using.

**Comment by jimmydorry** [comment]
Just knowing what gets banned the most would be pretty cool too (a player value for each ban).

**Comment by darklordabc** [comment]
On that topic, it would be great to know which abilities are getting picked most, and which are getting banned most. That data could be used in other gamemodes later on.

**Comment by Jexah** [comment]
100 bans is not overkill. Captain's Mode bans 10 heroes for both teams, and 5 heroes for each team (picks). This equates to one team only having (total_heroes - 15) available to pick from, so 15 heroes are removed from the pool. At on average 5 skills per hero, this is 75 skills. After taking into account the neutral skills, Captain's Mode removes about the same ratio of skills as 10 bans LoD.

**Comment by jimmydorry** [comment]
If anything, I think we need more bans... to force more originality.

**Comment by darklordabc** [comment]
1. In Captain's mode, picking and banning are interwoven, so you have a chance at picking the best heroes (read abilities) before they are banned.
2.  Captain's mode for Dota 2 is designed for the upper to high skill bracket of players. LoD all pick, has -to be polite- a lesser average skill level. Perhaps if all the players were highly skilled and knew of dozens of brutal ability combos, 100 bans would be more justified, but as it is, you only need to ban like  15 abilities to force most players to have to be original.

**Comment by Jexah** [comment]
That's exactly why it's 10 bans, so that if most of the players in the particular game are good, they can actually have a good match. Additionally, this is coming back to why zero bans is most popular, because most players just want to play OP stuff, aren't any good, and don't want 10 bans, 5 bans, 3 bans, or even 1 ban, because that's 10 OP skills that they potentially can't have.

Decreasing the number of bans in AP would not change the ratio of AP games with bans in them, this is my hypothesis.

**Comment by darklordabc** [comment]
//Decreasing the number of bans in AP would not change the ratio of AP games with bans in them, this is my hypothesis.//
I disagree. I know its a small sample, but myself would vote for the banning phase if it was 1 or 2 abilities. I personally dont vote for it because its too many abilities. I _expect_ there are others like me.

**Comment by jimmydorry** [comment]
What's your steam profile? Are you Knizzle?

**Comment by Jexah** [comment]
http://steamcommunity.com/id/darklordabc

kekvac

**Comment by darklordabc** [comment]
Okay, I've just played 4 custom games where bans were enabled and here were the results so far:

**First game**: 10 bans per player, but OP and LoD abilities were enabled (except troll combos)
**Second game**: 1 ban each.
**Third game**: 2 bans each, OP and LoD abilities enabled. 
**Fourth game**: 3 bans each.
Proof: http://imgur.com/a/buth1

This is only compiled in the last hour or two. I will keep going but I suspect its going to continue in this trend of low ability bans.

**Comment by Jexah** [comment]
https://getdotastats.com/#s2__user?id=76561198054179075

Nice stats bro.

**Comment by darklordabc** [comment]
Thanks?

**Comment by Jexah** [comment]
Which profile did you play all your games on?

**Comment by darklordabc** [comment]
Tony Abbott is my main one, but I have other.

**Comment by ash47** [comment]
Stats for ONLY custom and custom_bot: https://getdotastats.com/#s2__mod_f_filter?id=3

I rest my case @darklordabc

**Comment by jimmydorry** [comment]
It's the top right graph, if you don't see what you need to look at. 10 is obviously bigger than 1-5 combined.

![graph](http://i.imgur.com/fzn4nE4.png)

**Comment by darklordabc** [comment]
When, are these stats for all games that are hosted? Like, if I host a game, and start the game to test something solo, and then quit 5 minutes later, does that count in the statistics? 
Because the obvious problem here, is that 10 is the default settings for custom games. So if I test the something 15 times, and never bother to change the bans because its not relevant to the testing, that would count as 15 times "10 bans" were played? 
My point is that having it as the default, is problematic and may be skewing the statistics to 10 bans. Now if the bans were default to zero, and it was still 10 bans in the stats, then it would be an open and shut case, but as it is the default setting, its hard to prove that is what players are actually choosing to play with.

**Comment by Jexah** [comment]
So now you're saying that the best evidence that could possibly be obtained, is no evidence at all.

My only guess as to why you posted this issue in the first place, if not based on reason, is based on feeling. So then why are you trying to argue with the statistics we have? Why are you trying to use statistics to prove an emotional case? You really are all over the place with this one.

**Comment by darklordabc** [comment]
Its evidence, but there is an obvious problem with having 10 bans being the default. Especially if test games and abandoned games are considered. Emotions have nothing to do with it. And I would not be belaboring this point, if my experience was not so wildly different to what the "stats" are saying, which is why I suspect the stats are misleading in the first place.

**Comment by Jexah** [comment]
I wrote out a whole paragraph and realised that you are a lost cause. I'm sorry that you haven't reached enlightenment by playing LoD. I'm sorry LoD isn't your perfect little game. If you like playing balanced mode, vote for 10 bans. If you like playing imbalanced mode, vote for zero. If you want anything in-between, play custom. That is my advice for you on this topic moving forwards

Have a good day.

**Comment by darklordabc** [comment]
Have a good day too bro.

**Comment by ash47** [comment]
Your experience clearly doesn't cover the Chinese or Russian communities. From the sound of your "stats", it looks like you are just abandoning games in order to generate them, so, by your logic, your games don't actually count, since they were played to the end.

The amount of games where option selection happens and then people don't play is extremely low and neglectable.

**Comment by darklordabc** [comment]
![image](https://cloud.githubusercontent.com/assets/16277198/14889994/4704aea8-0da4-11e6-92a7-8e0a9aae2896.png)
What accounts for the the 2 being the highest amount of hero bans? Do you think people are choosing 2? Or do you think its because 2 is the default ban?

**Comment by ash47** [comment]
I'll just put it out there that the little time that myself and other
contributors get to work on the game mode was basically spent in this
thread today.

That figure basically shows that the hosts generally don't care about the
number of bans, hence, further proving the point that people don't care
about the number of bans.

For the record, it WAS set to five bans in all pick, and it was changed due
to many complaints that 5 was not enough.

Additionally, the default number of hero bans was set to 1 for the majority
of those stats, and the default number of bans was set to 5, only recently
was it changed to allow more than 10, people were simply maxing out the
number of bans, again, people asked for more than 10 bans.

The default settings have been driven by what people on the steam forums
have been asking for, the all_pick_fast map was added because someone like
you claimed they knew that every single game in custom had really low
respawn times and that people wanted to start at level 11, I added the map,
and it completely flopped, showing that his point of view was not that of
the majority of players.
On 29 Apr 2016 12:51 AM, "darklordabc" <notifications@github.com> wrote:

[image: image]
<https://cloud.githubusercontent.com/assets/16277198/14889994/4704aea8-0da4-11e6-92a7-8e0a9aae2896.png>
What accounts for the the 2 being the highest amount of hero bans? Do you
think people are choosing 2? Or do you think its because 2 is the default
ban?

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/ash47/LegendsOfDota/issues/251#issuecomment-215451319>

**Comment by jimmydorry** [comment]
@darklordabc it's a bit ridiculous to be asking for less choice or changing a default that is clearly changed by users that care (which happens to be the super majority). If you want to redirect your energies somewhere else, I am sure I can find something else for you to work on, that won't tie up these kind folk that work on LoD.

**Comment by darklordabc** [comment]
//only recently was it changed to allow more than 10, people were simply maxing out the
number of bans, again, people asked for more than 10 bans.//
That stat page says the stats were compiled only from the last week of games.

**Comment by jimmydorry** [comment]
Ignore the writing. It was a copy paste of the normal flags page, but pointing at a different data source. It's based on the data from the last 30,000 games played on the two custom maps.

**Comment by darklordabc** [comment]
So, its essentially a coincidence that in most custom games I play, with hero bans, 10 picks is not chosen? I'm to believe that in reality, there is lots of _other_ games happening, where 10 picks is the norm?

**Comment by jimmydorry** [comment]
1 / 10 games, roughly. Recording about 10 games a minute, so roughly one 10 ban game a minute.

Believe it or not, but the data is there.

**Comment by darklordabc** [comment]
So you don't think having 10 as the default, is skewing the data?

**Comment by jimmydorry** [comment]
Sure, but not enough to matter. People that don't like it can change the setting. It's a non-issue.

**Comment by darklordabc** [comment]
Its an issue because it is the justification for why it is 10 bans in all-pick map, where you can't change the settings.

**Comment by darklordabc** [comment]
I've been sitting in the [lobby list](http://imgur.com/3VxehV4), joining any custom game, regardless of region, and recording what bans the players use. Most custom games don't have any bans, but the ones that do, 10 bans is minority. Large majority are 1 to 5 bans.

5th Game: 10 bans - Host Appeared to be AFK
6th Game: 1 ban
7th Game: 10 bans
8th Game: 5 bans
9th Game: 3 bans, op abilities enabled
10th Game: 1 ban, lod and op abilities enabled
11th Game: 2 bans
12th Game: 1 ban

**Comment by darklordabc** [comment]
I've been sitting in the [lobby list](http://darklordabc.imgur.com/all/), joining any custom game in any region and recording the amount of bans the admin used. Most games don't have bans, but the ones that do, 10 is rare, and the vast majority are between 1 to 5. 
**5th game:** 10 bans - host appeared to be afk
**6th game:** 1 ban
**7th game:** 10 bans
**8th game:** 5 bans
**9th game:** 3 bans, op abilities enabled
**10th game:** 1 ban, lod and op abilities enabled
**11th game:** 2 bans
**12th game:** 1 ban
**13th game:** 2 bans, op and lod abilities enabled

Screenshots: http://imgur.com/a/buth1

**Comment by ash47** [comment]
How are you joining ten games per minute? If you're leaving in games in
order to do this, that's a dick move.

**Comment by darklordabc** [comment]
Yeah I don't feel good about abandoning the games, but my motives are pure and I rationalize it that what I'm doing is for the greater good of the mod.

**Comment by jimmydorry** [comment]
He abandoned 8 of his last 11 games. And yes, those appear to all have abandoned at the start of the game (as in he had level 0, while everyone else was like 20+).

That's disgusting.

	{
	  "result": [
		{
		  "steamID32": 93913347,
		  "numGames": 58,
		  "numWins": 1,
		  "numAbandons": 8,
		  "numFails": 0,
		  "lastAbandon": "2016-04-28 17:11:35",
		  "lastFail": null,
		  "lastRegular": "2016-04-28 01:50:24",
		  "dateUpdated": "2016-04-28 23:42:42"
		}
	  ],
	  "schemaVersion": 1
	}

**Comment by ash47** [comment]
You can't record more data than 100% of matches, I'm recording 100% of
matches, and they tell a different story to what you're telling, the code
has even been changed to fix the flaw you talked about, I'll look at the
stats after enough sample data has been collected.

**Comment by darklordabc** [comment]
Pfft, get over yourself Jimmy. 
Ash, I could play 1000 more matches, and I would bet the farm, that 1 to 5 bans continues to be the majority in all those games (with bans enabled).

**Comment by darklordabc** [comment]
At a certain point, you have to conclude that something is wrong with the statistics collection process.

**Comment by ash47** [comment]
Explain the stats then? My stats aren't getting pulled out of thin air, my
stats aren't based on a gut feeling, my stats are nothing but raw data.

I already have a solution to your problem anyways and it's partially
implemented, it's just fun to watch you make a fool of yourself.

**Comment by darklordabc** [comment]
Lol. Yeah alright buddy. All i know is, I much rather be right and look foolish than be wrong.

**Comment by jimmydorry** [comment]
Why not both? I was sympathetic to your cause (if it could be backed up with data), until you ruined the games for 72 other people.

**Comment by darklordabc** [comment]
Morally its a grey area. I needed to collect data to solve a greater issue, and the only way to collect data, was to conduct tests by joining servers I had no chance of playing on. Was I meant to play for an hour on a Brazil server where my ping was 1000? 
I don't feel great about leaving those servers, but its not black and white like you think. And if the _ridiculous _default 10 ban limit eventually does get overturned based on my data, then it would benefit those people whose games I negatively effected (i.e. people who like bans but are forced to play custom games because all_pick_6 has too high a ban limit).

**Comment by darklordabc** [comment]
And having leavers does not ruin LoD games. Every game of LoD I've ever played had at least 1 leaver at the beginning.

**Comment by ash47** [comment]
It would never benefit those people because those people are playing custom

**Comment by darklordabc** [comment]
They are probably playing custom _because_ all pick is currently only good for people who don't like bans. I would play all pick much more often, if I knew there was a chance of actually having reasonable ban limits.

**Comment by ash47** [comment]
I'm pretty sick of the constant notifications. Once the new data is in in roughly a week, me and my trusted advisors will revaluate the default options.

**Comment by ash47** [comment]
Here is fresh data from the last week, which ONLY includes data for custom matches where players strictly selected "custom" settings, and did NOT use presets:

![image](https://cloud.githubusercontent.com/assets/3754510/15109339/4e6b2b7c-161e-11e6-80a3-96b61e12125b.png)

**Comment by ash47** [comment]
10 still remains the dominant choice.

**Comment by LODonly** [comment]
Please change default quantity of skills to ban from 10 to 2...5. And reduce banning phase to 30 sec. These changes will make banning more popular. Currently it takes a lot of time and 100 skills to ban is too much. Banning phase is skipped more often then used. I think it's not only because 10 abilities, but because more extra time to wait till game is started. 30 sec is enough to make fast bans. AP mode is considered to be a fast started and set game.

**Comment by jimmydorry** [comment]
About 13% of games have host banning. About 57% of games have a max abilities banned set to 0, meaning that close to 50% have at least 1 ban per player. If 2 or 5 were better choices, you would see more games with option, instead almost all stick to 10 or increase it.

14% of games have "voting banning enabled", but i don't remember what that means.

https://getdotastats.com/#s2__mod_f?id=3

Overall, I don't see much reason to change what seems to be working well. If they want a faster banning phase for their better balanced games, hosts will change the parameters made available to them. Significant trends in parameter usage would reflect what hosts are doing, and indicate whether the default should be changed.
