### ISSUE TITLE
SPIRIT FORM

### ISSUE THREAD

**Issue by Hm-mm** [ash47/LegendsOfDota#256]
While in SPIRIT FORM of KOTL, whenever a he uses a casting spell like black hole, death wards or any spell that is lasting for a short period of time. make it like KOTL using his illumnate. The seperated spirit will do the casting for him.

**Comment by Jexah** [comment]
This is dumb.

**Comment by Hm-mm** [comment]
Lol, coz spirit form is useless. no one use it. New meta.

**Comment by Hm-mm** [comment]
anyway, it's just a suggestion. @ash47 is still the one who decides

**Comment by darklordabc** [comment]
I know what you are saying. You are saying that if you have spirit form on, all channeling abilities, like black-hole, shackles and fiends grip, should be be channeled separately and be uninterruptible like illuminate in spirit form mode. I like the idea, with a couple of caveats. It may be too hard to program and not worth the effort, and it may be OP. Like if you have spirit form and you fiends grip somebody, there would be no way for the enemy to break it, so its guaranteed to go to its full completion. But giving that spirit form is literally a useless ability on any other hero besides Kotl, I think its a good idea. 

The bigger problem, is that KOTL ultimate is broken on any other hero besides KOTL. The ability says getting aghs will give you permantely spirit form and vision, but it gives you neither if you play as a different hero model. I think this is a similar problem to other ultimate that need to be fixed.

**Comment by ash47** [comment]
This is not really feasible, it would require recoded every single spell. The way that illuminate works is that when you change to spirit form, it swaps the skills out, there are two illuminate spells. This is especially hard I don't have the source code to make the other spells.

This spell would simply be thrown into the overpowered bucket along with Multicast and Witch Craft :/
