### ISSUE TITLE
URGENT: Dota2.exe crashes on game start.

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#261]
![image](https://cloud.githubusercontent.com/assets/16277198/15015086/306a1fb8-124d-11e6-8c12-498fb0e625a7.png)
Game crashes on start. If you restart Dota 2, you can reconnect to the game and everything works fine, but initially it just fucks up.

**Comment by darklordabc** [comment]
In my local client, I had this error in the console "[   Developer ]: ..dota_addons\testlod\scripts\vscripts\addon_game_mode.lua:24: attempt to concatenate local 'versionNumber' (a nil value)"
I went into the file, and just commented out the print line, and the game worked. Maybe this is the problem with the live version? Idk, just a guess.

**Comment by ash47** [comment]
Should be fixed.

**Comment by darklordabc** [comment]
Its still crashing!

**Comment by ash47** [comment]
Can you try pressing "uninstall" then reinstall"right after?

**Comment by darklordabc** [comment]
Testing now

**Comment by ash47** [comment]
I've forwarded the issue to Valve, if you can upload a crash report from
your dota 2 folder, and give some system specs, I'll pass the additional
information to Valve.

**Comment by darklordabc** [comment]
I tried it once, and it loaded for me, tried a second time, and it crashed again :/ 
btw love the stats. Ugly as sin, but its a great addition.

**Comment by darklordabc** [comment]
Crashed again. Maybe you should roll back to when it was working?

**Comment by ash47** [comment]
I don't have a copy with me so I can't until I get home.

**Comment by darklordabc** [comment]
Anything I can do to help?

**Comment by ash47** [comment]
Is this fixed? I think it was the stats that did this.

**Comment by darklordabc** [comment]
Yeah its fixed
