### ISSUE TITLE
Aghs reduces Invoker abilities to lvl 1.

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#276]
![image](https://cloud.githubusercontent.com/assets/16277198/15090004/c190e574-1457-11e6-85d2-fdb25bc3f5af.png)

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/16277198/15089993/fd9b3b2e-1456-11e6-8903-b367be7137bf.gif)

**Comment by ash47** [comment]
Please check for existing issues: https://github.com/ash47/LegendsOfDota/issues/165
