### ISSUE TITLE
Make Aghs Unlocked Ability require lvl 6

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#287]
Walrus Kick is WAY too strong for a lvl 1 ability. 350 damage, massive slow, and 8 second cooldown for 100 mana, is very powerful early game. I suggest that all abilities that get unlocked by aghs, require lvl 6 to use. These abilities are designed for late game usage, and were never intended to be used early game. Burrow is also very strong early game.

**Comment by Jexah** [comment]
This mode is not balanced nor standardised, and so there are bound to be skills like this. It's just part of the game mode.

**Comment by darklordabc** [comment]
So unfair and overpowered abilities are a feature? If that was the case, why do we have troll combos in the first place?

**Comment by Jexah** [comment]
Automatic Aghs Upgrade mode has the same support as Troll Combos Allowed mode, which is exactly none. Those modes are there for shits and giggles for folks who like imba stuff. If you don't like imba stuff, play the default game mode.

**Comment by darklordabc** [comment]
I'm not talking about free aghs mode, I'm talking about picking those abilities in normal mode. Walrus kick can be picked without aghs.

**Comment by Jexah** [comment]
Oh, my bad. I see where you're coming from now. What I was saying doesn't even make sense in the context of LoD. So the deal with those skills that only have one point, is that they are value points, and that is a core mechanic of LoD. Finding a balance in your team between early game, mid game, and late game is important.

Walrus Kick is better than Walrus Punch early game, but worse late game. Assimilate is better than Infest early game, but worse late game, etc.

**Comment by darklordabc** [comment]
I know what your saying, but I still disagree. Walrus kick is an ultimate ability, and most ultimate abilities require lvl 6, even in LoD.

**Comment by Jexah** [comment]
Technically it's not. In a regular game of Dota, if you assume 5k starting gold, a player can have Walrus Kick at level 1. It's in the same vein as Hybrid, Burrow, Chakram, and Eyes in the Forest, in that it does not actually upgrade the ultimate of the hero, rather it adds an ability to the hero.

**Comment by darklordabc** [comment]
Its counts as an ultimate when you are in skill selection. So I think that technically it is.

**Comment by Jexah** [comment]
> In a regular game of Dota, if you assume 5k starting gold, a player can have Walrus Kick at level 1. It's in the same vein as Hybrid, Burrow, Chakram, and Eyes in the Forest, in that it does not actually upgrade the ultimate of the hero, rather it adds an ability to the hero.
