### ISSUE TITLE
Suggestion: Make two pinned threads on steam. bugs + suggestions/balance/feedback

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#289]
I just thought it would be an improvement, take it or leave it, either way not much difference. 
![image](https://cloud.githubusercontent.com/assets/16277198/15272811/9088dde8-1ac8-11e6-8af4-b50eefc1596c.png)

**Comment by TheRisen41** [comment]
maybe also one for reporting troll combos?

**Comment by darklordabc** [comment]
I thought about that but it may be too many pinned posts.

**Comment by ash47** [comment]
Probably won't happen :/ It's not like there is so much discussion on the forums that I dont see everything.

**Comment by darklordabc** [comment]
Closing
