### ISSUE TITLE
Adding new abilities and/or improving redundant abilities 

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#290]
This isnt really an "Issue". In the far far future, what do you guys think about modifying and adding custom abilities. I'm just curious if you have any thoughts on this topic. I'm not sold on the idea myself.

**Comment by ash47** [comment]
I was going to add essence shift but two variants that give strength and int instead of agi, I think that would be fun XD

each attack steals 3 of each attribute, ouch!

**Comment by TheRisen41** [comment]
I like this idea. It would be cool to see what people would come up with. 
Also ash how about INT morph? :D

**Comment by ash47** [comment]
I think it would be interesting to come up with a way to make agi / str morph work both both ways with only one slot.

**Comment by TheRisen41** [comment]
True maybe tap strength morph and double tap agi?

**Comment by darklordabc** [comment]
Can you make autocast goes one way, and toggling it goes another?

**Comment by darklordabc** [comment]
Also, what I think would be nifty, if we cooperated with other mods, and imported their custom abilities, grouped them in the skill picker window so it was obvious what mod it came from. I suspect many developers would not be keen for this idea, because they probably spent hours making those abilities and want them exclusive to their gamemode, but I reckon a couple might agree.

Imba Dota has dozens of modified abilities, and Crumbling Island Arena has at least a dozen very polished skills. Many of these skills would be OP, but many are just plain cool ideas that can be balanced (enough) pretty easily. 

So other mods get free advertising, and LoD gets a whole suite of cool and fun new abilities. Thoughts?

**Comment by TheRisen41** [comment]
Would be really awesome to have the imba skills in lod :). But like you said i dont think that many modders will gree with this because while it advertises for that mod it may also drive some players away from that mod because why playing that mod when you have all the skills avaible here plus more customization.

**Comment by darklordabc** [comment]
Well for the crumbling arena game, the game play is so different from dota or lod that i dont think it would sap its fan base too much. But ur right, it might be hard to find a developer keen.

**Comment by darklordabc** [comment]
Btw the developer for Crumbling Arena said we could use his abilities.

**Comment by ash47** [comment]
This has been partially implemented, a new issue has been raised for each of the custom abilities that have been discussed, this issue is no longer needed.
