### ISSUE TITLE
Game does not precache custom images for hints

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#295]
Console spits out 
**File error loading resource header "panorama/images/custom_game/hints/hint_empowering_haste_png.vtex_c" (Error: ERROR_FILEOPEN)**
when it tries to load the custom PNG for that hint. A solution is to include the image in a CSS file, and for some reason that will cache the file and make the vtex_c file.

**Comment by ash47** [comment]
I think I removed that precache in a recent commit thinking it wasn't needed.
