### ISSUE TITLE
Error accessing custom game files.

### ISSUE THREAD

**Issue by Teok25** [ash47/LegendsOfDota#296]
Now I'm not sure if this is a problem with reborn, or the mod, but from the arcade screen, there are 13 maps, which include error, tutorial_m2, dota_685, and blackmap. no matter what map I pick, it comes up with the error "Error accessing custom game files." when I hit play. This isn't the case with other mods, so I'm not sure what's going on

**Comment by darklordabc** [comment]
Is this from vanilla Dota 2 or from the Workshop Tools? 

This is what I see when I go to host a game of LoD. 
![image](https://cloud.githubusercontent.com/assets/16277198/15289465/b8324c6a-1bb5-11e6-9ae5-c200d2ffabca.png)

**Comment by Teok25** [comment]
The problem fixed itself after i played a normal match for some reason, It might have just been Dota.

**Comment by ash47** [comment]
Seems like a non problem.
