### ISSUE TITLE
Vengance aura

### ISSUE THREAD

**Issue by Adalennor** [ash47/LegendsOfDota#30]
Vengance aura on towers = game crash

**Comment by Adalennor** [comment]
Well to be more specific if a tower with vengeance aura is killed and the unit killing it gets a debuff that reduces damage until vengancefull spirit respawns as there is no vengeancefull spirit i'm guessing that cause it to crash.

**Comment by ash47** [comment]
Cool find :)

**Comment by ash47** [comment]
Banned on towers. Fixed.
