### ISSUE TITLE
custom_bot crashes if you play as Riki

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#300]
1. Start a custom_bot game.
2. Continue to hero/skill selection screen (dont change any options)
3. Choose Riki as hero
4. Ready up
5. It Crashes

It seems picking Riki in custom bot, causes a crash. Perhaps there is other buggy heroes?

**Comment by ash47** [comment]
Cool, usually this happens when the hero has some kind of aura that the
bots need to hook which isn't there, likely his invisibility, easy to fix,
just needs some debugging to work out which ability I can't remove, and
then add it to the list of skills to leave on the hero.
