### ISSUE TITLE
Prioritize Hero Stat Information

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#306]
I recommend having the first segment house all the most relevant stats, the ones that vary the most. 
So something like this:
![image](https://cloud.githubusercontent.com/assets/16277198/15397974/5766d85c-1e25-11e6-9814-199620e7f8ea.png)
If you approve I can make a pull request, otherwise feel free to close this issue.

**Comment by Jexah** [comment]
I like the idea of grouping movement speed and attack range with the damage and BAT, but it feels like a lot of content before the stats. Maybe move armor to the third category, and attack point to the fourth, and I think it'd be good.

Out of curiosity, do the base HP, base mana, and base mana regen (besides Techies) actually change between any of the heroes? If not, would it be a good idea to remove them from the stats list here?

**Comment by TheRisen41** [comment]
@Jexah Base HP is 200 and base mana is 50 for every hero. Hp regen is different from hero to hero.

**Comment by ash47** [comment]
I don't care. make a pull request, if it's good, I'll merge it.

**Comment by ash47** [comment]
The other way we could go is:

if(hp != 200) {
    // show hp line
}

**Comment by darklordabc** [comment]
#310

**Comment by darklordabc** [comment]
#324
