### ISSUE TITLE
Latest version (1.4.3) giving error in scripts/vscripts/SkillManager.lua

### ISSUE THREAD

**Issue by elnasty** [ash47/LegendsOfDota#31]
Hello my name is Stanley and thank you for your amazing work. 

I apologise if I'm out of line posting here, but the latest version (9/2/2015) has been giving this error in the console.

"scripts/vscripts/SkillManager.lua:71: bad argument #1 to 'pairs' (table expected, got number)
Failed to execute script: scripts/vscripts/SkillManager.lua:71: bad argument #1 to 'pairs' (table expected, got number)"

I have successfully gotten the server to run and people to connect prior to this. However after updating today then was I met with this new error. Reverting back to the 2nd most latest version I have (1.2.4) removes this error.

I noticed the new step in Starting a source1 server, where dota_fixed.bsp needed to be renamed and replacing dota.bsp and have done as instructed.

Thank you for your time and hard work.

**Comment by ash47** [comment]
Added a warning in the console.

You are trying to run an uncompiled version of Legends of Dota. You need to download a compiled version, or compile it yourself.

https://github.com/ash47/LegendsOfDota/releases

**Comment by elnasty** [comment]
Wow thank you for the super quick response!

Sorry for wasting your time. It had already become a habit to download the zip and take the lod folder ><

Thank you again!
