### ISSUE TITLE
Ethereal Jaunt should not be counted as invisibility. Essence + Ball lighting should be troll combo

### ISSUE THREAD

**Issue by darklordabc** [ash47/LegendsOfDota#316]

**Comment by ash47** [comment]
We were working on better categorizing skills, @Jexah built a tool to help
with this, maybe @darklordabc could do this?

**Comment by darklordabc** [comment]
I can do it. What's the details? What is this tool?

**Comment by ash47** [comment]
@jexah needs to give you access

**Comment by darklordabc** [comment]
To what?

**Comment by ash47** [comment]
To the tool that makes classifying stuff much more stream lined

**Comment by darklordabc** [comment]
Well while Jexah is taking his time to reply can i get my friend to work on creating those 2 new essense shift abilities? For int and str?

**Comment by darklordabc** [comment]
Or is there something more pressing to work on.

**Comment by ash47** [comment]
It's pretty trivial, just take the one from spell library

**Comment by darklordabc** [comment]
I will.

**Comment by ash47** [comment]
go nuts: https://github.com/ash47/LegendsOfDota/blob/master/src/scripts/kv/flags.kv
