### ISSUE TITLE
[Troll Combo] Spawn Spiderlings + Battle cry

### ISSUE THREAD

**Issue by TheRisen41** [ash47/LegendsOfDota#317]
This combo allows to destroy towers in under 5 seconds at level 6 If you have +10 spiderlings/spiderites which is achiveable most of the time they deal 700+ every 1.35 seconds for 6 seconds when battle cry is activated. Now this is only at level one battle cry and with 10 spiderlings/spiderites. 
With 20+ spiderlings and lvl 3 battlecry they have a dmg output of 2.600+ dmg per 1.35 seconds. At this point you can destroy a tower/rax instantly. Of course this build is easily countered by any cleave/ aoe magic dmg build but you can easily just rat doto with spin web. What do you guys think should this be a troll combo?

**Comment by Jexah** [comment]
I don't think it should be a troll combo. It requires 3 skills to work, Battle Cry has a large cooldown in which the hero is useless, the build can be destroyed by banning a single skill, and spin Web is usually banned. Most importantly though, it is easily countered.

**Comment by darklordabc** [comment]
I'm voting against it being a troll combo.
I just tested it, and its not that easy to pull off.
First you need to have true-form ultimate ability to even be able to skill battle cry. So thats 3 skills minium, true form, battle cry and some kind of spawning skill (like spiderlings). |
And secondly, battle cry only lasts for 6 seconds.
But I do admit, it is a ridiculous amount of damage for spawned creatures, and with plenty of spides you could easily wipe a tower in seconds. Nonetheless I dont really think it should be a troll combo.

**Comment by ryanwilson112** [comment]
Voting against also. Very good early game once it hits 6, but can't hold out against most other builds late. And as you say, it has one very clear counter, AOE of any kind. 

Just played against one such combo today. The guy picked OD. Had spiderlings, feral impulse, web spin, battecry, shapeshift and true-form. We had no bans, all-pick 6. 

Needless to say, he dominated the lane, ratted the fuck out of us and got racks under 12 minutes. Then it was a bit more complicated as Mr AOE man had Wyvern's Curse, Fissure and Echoslam. One good echoslam landed him the gold and exp to prevent all future pushing. And two of us built Shivas and bought sentries. So we didn't rely on AOE man. Won the game in the end. 

The amount of space it creates is amazing though.

**Comment by TheRisen41** [comment]
Yeah true it has too many weaknesses to be a troll combo. I will close this.
