### ISSUE TITLE
Experiencing repeated crashes with particular skillbuild

### ISSUE THREAD

**Issue by elnasty** [ash47/LegendsOfDota#32]
Hello it's me again,

Last night I wanted to try out a skillbuild and the server crashed on me, I chalked it up to being unlucky and went to bed but this morning I was able to recreate the crash consistently. Everything is fine until a hero is picked. Up until that point, choosing options, picking and banning skills, browsing the hero pool is fine. The console doesn't seem to say much. 

The skill build is:

1. Wyvern's Artic Burn
2. Nightstalker's Hunter in the Night
3. Slardar's Bash
4. Troll's Berserker's Rage
5. Tiny's Grow
6. Nightstalker's Darkness

I'm guessing it's Wyvern's skill? And if this isn't new information to you I'm sorry, again! >< Also side question, is there any way to have stone caller remnants? My best bet was to put the skill Stone Remnant in it's original D spot and pick Earth Spirit, no luck though.

![wwq_error](https://cloud.githubusercontent.com/assets/10924425/6242208/7d921eec-b765-11e4-82dc-328c5a38e76f.png)

**Comment by ash47** [comment]
Stone Remants = idk, I can look into it for you.

I'll check this build out, can you say what hero you picked? Chances are it is the hero in particular.

**Comment by ash47** [comment]
![capture](https://cloud.githubusercontent.com/assets/3754510/6261007/300c7e24-b83c-11e4-8421-f9fd4c6a62db.PNG)

Works 100% for me, need to know the hero in use? Which hero did you use?

**Comment by elnasty** [comment]
Hello again again, thank you for taking time to look into this.

I've used Abaddon, Beastmaster, Nightstalker and Venomancer. With the instant closing upon hero pick. :\

![2015-02-19_00001](https://cloud.githubusercontent.com/assets/10924425/6261743/6fbfbdfe-b82f-11e4-845f-61322eda43c1.jpg) Forcing the same skill build just without the Winter Wyvern's Q, I'm allowed to enter the game. Just noticed you updated to 1.4.8, I'll update as well as do a clean re-install of the files.

Thank you again.

**Comment by ash47** [comment]
Oh, you're running your own server? If I knew that:

You need to update the server files themselves (as in, recopy your doto directory)

**Comment by elnasty** [comment]
Ah! That actually makes ton of sense. Feeling pretty silly now. 

After coping the bin and dota folders over I now have this new error when starting srcds. I've never seen it before and didn't find anything on Google.

(token -1) : Discarded rule because of invalid criterion isibility
(token -1) : Discarded rule because of invalid criterion ispowerupinvisspectrecompendium
(token -1) : Discarded rule because of invalid criterion isibility
(token -1) : Discarded rule because of invalid criterion ispowerupinvisspectrecompendium

Spectre Compendium? Gosh I'm terrible at this, so sorry for the trouble.

**Comment by ash47** [comment]
Ensure you are using the last metamod and source mod snapshots, and latest d2fixups, verify game info.txt

**Comment by elnasty** [comment]
Any other things I could look out for? The snapshots are supposed to be the latest in the dev branch is that correct?
