### ISSUE TITLE
multicalt + divide-we-stand

### ISSUE THREAD

**Issue by zblcm** [ash47/LegendsOfDota#33]
When having multicast and meepo's divide-we-stand at the same time, one of the divided hero cast, the main hero will cast the spell several times.

**Comment by ash47** [comment]
The best I can rreally do is blacklist them together, the way multicast works, when a spell is used, it fires an event, the info I get is basiclly the playerID that issued the command, and the spell name. No way to know which meepo casted it, I could, maybe guess based on which has the highest cooldown remaining, but it will probably have a hhuuuge performance hit >_>

**Comment by ash47** [comment]
Basically, I made that a trollcombo >_>, most reasonable thing I can do, really...

**Comment by zblcm** [comment]
Yes that is really a troll combo ...

Can a passive datadriven ability be made to listen to OnSpellStart event?
If it works then you can use lua script to catch the caster ...

2015-02-25 4:53 GMT-05:00 Ashley Schmid <notifications@github.com>:

**Comment by ash47** [comment]
Feel free to try
