### ISSUE TITLE
Spectator Bug

### ISSUE THREAD

**Issue by BlueNagrom** [ash47/LegendsOfDota#35]
Whenever i try to join anyone of the servers I join as a spectator, I've redone everything multiple times and nothing has changed.

**Comment by ash47** [comment]
If your name starts with an S, you will be assigned as a spectator! If you are playing on my servers, you need to get in before the match starts, as there can only be 10 players, including bots.

Can you give more details? Is it your own server?

**Comment by BlueNagrom** [comment]
My name starts with an s, thanks for the heads up.

**Comment by ash47** [comment]
R for radiant, D for dire, S for spectator ;)
