### ISSUE TITLE
gdsOptions.json missing multiplier options

### ISSUE THREAD

**Issue by SinZ163** [ash47/LegendsOfDota#37]

**Comment by jimmydorry** [comment]
When you update it, I can drop it into the database ![GreyFace](http://dota2.photography/public/s/GreyFace.png)

**Comment by ash47** [comment]
Can you get me the latest file so I don't waste my time updating mine?

**Comment by jimmydorry** [comment]
Sure, I thought you already had it. http://pastebin.com/1GyPM6uG

**Comment by ash47** [comment]
Finally fixed
