### ISSUE TITLE
Spell Multiplier Issues

### ISSUE THREAD

**Issue by ash47** [ash47/LegendsOfDota#39]
sticky tar broken - insta kills everything
**track cast range isn't multi**
eyes in the forest trees sight range isn't multi, also doesn't work with overgrowth
duel broken
**glaves bounce range isnt multi**
**timber chain cast range not multi**
shadow poison doesn't do damage, **cast range not multi**
**burrow strike cast range isnt increased**
**witchcraft doesn't reduce cooldowns**
unstable concoution can't be thrown also cast time over head x5, also crashs client if they try to spend skill points after (from cast skill not working
**broodmother as hero crashes server**

**Comment by ash47** [comment]
arcane orb on treant protector, once used crashes game
spirt bear not x5 like tooltip
rot doesn't work on lone druid
can't launch fire spirits, or stop icarus dive, or sunray as phoenix
5 towers per lane is broken, 2nd thru 4th towers are always invunrable

**Comment by ash47** [comment]
Veroalla: Found some "broken" spells in LOD x5. here is list:
Veroalla: anchor smash
flaming fists 310% chance lol
gush
amplify damage
shapeshift ulti, maybe OP?
greater bash/flamebreak outside map crashes server
atrophy aura 210% decr. dmg
necro aura -1%
ice blast ulti kill and scatter threshold op
troll ulti crashes server!
incap bite
earth splitter, titan. oneshot?
untouchable
degen aura
Veroalla: sorry, just saw you updated to 2.2.1 :)
Veroalla: techies suicide squad ALWAYS crashes server on all multipliers

**Comment by ash47** [comment]
Progress being made, I am bolding the issues as I think I have fixed them, will be pushing this patch out later :)

**Comment by zimberzimber** [comment]
Another thing concerning Sticky Napalm.
When using Arcane Bolt (presumably all targeted spells or spells with stat modifier) crashes the server.
