### ISSUE TITLE
Some Stuff

### ISSUE THREAD

**Issue by Chuave** [ash47/LegendsOfDota#40]
Hi Ash. I love your work :)

1) Host selected 4 Towers per lane. After the 1st Tower was destroyed the next one didnt become a valid target for attack. I tried attacking and planting a Sentry next to it with no results. Creeps would ignore and keep walking. Screenshot of creeps in throne after ignoring Towers: http://imgur.com/WLsFuYj

2) Morph Str has failed to work for me in some heroes from time to time. Cant reproduce the bug to know what triggers it.

3) When host goes afk before locking the set up for the game there is no timmer or anything, which in returns means the server is stoped for as long as the host remains afk. I have seen this happening several times. Maybe add a timmer to autolock after some time?

4) If you give Infest Bear into something and then recast Bear (not sure if dead of the Hero, infested target or leveling up Bear also procs this issue), the hidden Bear will be teleported to the position where you recasted it. At that point you cant use Bear anymore. it will not follow the infested target, nor it will uninfest even if target and hero dies.

5) If you give Bloodseeker's Thirst to a tower it will get the DMG boost but it will not reveal heroes under 30% HP.

6) When you get Agh on a hero with Divide We Stand and you have another ult with an Agh upgrade your clones dont get the Agh upgrade, only main hero gets Agh upgrade.

**Comment by ash47** [comment]
Only going to look into #1 right now, you using the workshop version, or the source1 version?

#2 occurs when you have too many abilities, some abilities, like morph, take up 2+ ability slots, there are 16 in total, one is taken by stat boosts, if the hero has skills in the gui, 4+ are taken by those slots, it adds up FAST

**Comment by ash47** [comment]
Tower's should now be fixed <3 2.2.2

**Comment by Chuave** [comment]
I was using source1.

Ty for your efforts :)
