### ISSUE TITLE
Dire Creep spawn bug

### ISSUE THREAD

**Issue by xshad3** [ash47/LegendsOfDota#43]
After played LoD with fast neutral spawn i found out that dire camp next to top rune is kind of bugged.
There is aways an creep spawned at hill next to camp.
![2015-05-12_00003](https://cloud.githubusercontent.com/assets/12416258/7596117/0b7e050c-f8f4-11e4-93a5-ee843a3ebcc5.jpg)
![2015-05-12_00001](https://cloud.githubusercontent.com/assets/12416258/7596118/0b8209e0-f8f4-11e4-8d64-1a90ec8c3e55.jpg)
![2015-05-12_00002](https://cloud.githubusercontent.com/assets/12416258/7596119/0b8692e4-f8f4-11e4-95d3-c8affa455151.jpg)

**Comment by ash47** [comment]
Not a whole lot I can do about this issue
