### ISSUE TITLE
Octarine + Witchcraft

### ISSUE THREAD

**Issue by aidant19** [ash47/LegendsOfDota#44]
Currently, witchcraft is applied after the lowered cooldown of octarine core, so it seems it may be lowering cooldowns more than intended. For example, assassinate with a level 3 cooldown of 10 seconds is reduced by 25% to 7.5, then by witchcraft's 4 seconds to make it 3.5 seconds. Alternatively, applying witchcraft before octarine core would lower it first to 6 seconds, then to 4.5. While not marginally different, it seems more logical and does not stack quite as oddly.

**Comment by ash47** [comment]
So you think it should lower cooldown by (level * 0.75) if you have the core?

**Comment by aidant19** [comment]
Yes.

**Comment by ash47** [comment]
Do you want this so the overall cool down reduction is less? Or is there some logic behind it?

My logic is that it takes off four seconds from the value the cool down reads XD

**Comment by aidant19** [comment]
If I remember correctly, when death prophet herself gets the ability, the actual cooldown goes down as listed. So implemented in game, it should be witchcraft's reduction first, then octarine core.

**Comment by ash47** [comment]
That's fair enough, I'll do it when I can :)

**Comment by aidant19** [comment]
Thank you!
