### ISSUE TITLE
toggle between skills

### ISSUE THREAD

**Issue by ghostlystrike** [ash47/LegendsOfDota#45]
Hi !

so i made my dota server, Every things are fine ! but if i choose more than 6 slote and want to toggle between skills server just got crashed and restarted...!

as i said every things work just fine if i only choose 6 slote and 4 regular ability + 2 ulti !

thanks million for your help!

**Comment by XAgent1990** [comment]
what abilitys do you pick, I noticed that also the official servers crash if you pick 10 or so of the same item, and then if you toggle or kill on the skill ability button it crashes

**Comment by ash47** [comment]
I know why, will fix this weekend if I get time

**Comment by ghostlystrike** [comment]
i do really Appreciate your work mate!

**Comment by ghostlystrike** [comment]
so is this problem solved?

**Comment by ash47** [comment]
That is correct, I just rolled out 2.3.0 which has the fix in it

**Comment by ghostlystrike** [comment]
thank you mate!

sorry for bothering you again, but may you tell me where i need to put these new files? i mean what directory and folder? tell me exact path please!

**Comment by ash47** [comment]
You just replace the old files
