### ISSUE TITLE
Creep Skills Bugs

### ISSUE THREAD

**Issue by XAgent1990** [ash47/LegendsOfDota#46]
-Caustic finale always casts explosions when the creeps attack
-Atropophy aura doesn't increase the damage of creeps (Edit: Rarely it acually does on single ranged creeps, havent seen on other creeps yet)

**Comment by ash47** [comment]
With asrophy aura, are you sure that both sides don't have this skill, and hence, they cancel each other out?

thinking I will just ban caustic finale on creeps

**Comment by XAgent1990** [comment]
Only radiant had it and they didn't get the effect that gives extra damage. The negative aura works though.

**Comment by ash47** [comment]
Should I just block that skill?

**Comment by XAgent1990** [comment]
I don't think you have to, because it's nothing op, it's just the problem that it is not as strong as you think it would be
