### ISSUE TITLE
Troll Warlord's Berserk's Rage not changing hero to ranged. Also, the max skill level doubling in latest patch doesn't show up.

### ISSUE THREAD

**Issue by mgb20092010** [ash47/LegendsOfDota#48]
Not sure how fixable this is since it's a unique skill, but Berserker's Rage won't turn a hero into ranged. It will change the stats, armor gain, etc. fine but does toggle melee/ranged. Tested on Antimage. Another minor bug I found with this is that when I selected 12 skills (12 regular, 12 ultimate) and put Thirst as the final skill on the second page, it didn't show up in-game and did not apply to the hero (tested twice on Antimage, it essentially is like I did not even select Thirst).

For the max skill level doubling option, it doesn't seem to be showing up on the customization page when you're setting up the game. Edit: Ignore this last part, I'm an idiot and didn't look under skill multiplier. Although, there are still some bugs for this option since it's new. Abaddon's Ultimate tooltip says it goes down under 20 seconds, but once you level it past 3 the cooldown goes back up to around 40 seconds.

**Comment by ash47** [comment]
I chop it down to you can't read. It clearly says double skill level option is under the custom spell power menu, it also says to pick a hero that has no skills or risk not getting all your skills when using 12 slot mode, anti mage does have skills in the selection UI in the source 1 version.

BR is not meant to change you to ranged, it's meant to change you from ranged to melee, which doesn't even make sense from a melee hero to test from.
