### ISSUE TITLE
[Suggestion] Double level abilities

### ISSUE THREAD

**Issue by leopupin** [ash47/LegendsOfDota#49]
I see that this can overload, but would be better if double spells levels were another option aside so you could combine the spells multiplier and double spells levels

**Comment by ash47** [comment]
No, that becomes overly complex, already sitting on 10 versions of witch craft, this will change it to 16 versions!

**Comment by ash47** [comment]
Plus CSP values are already stupidly high!

**Comment by ash47** [comment]
You understand that the point of doubled levels is to try to be a more balanced way to buff up spells, right? CSP is in no way balanced at all, adding doubled levels would basically be like adding 40x mode, as it stands, many of the doubled levels skills are sitting on their max values, meaning, if they go any higher, they will be beyond OP, so CSP and doubled levels won't even do anything in many cases

**Comment by ash47** [comment]
Here is how ugly the code looks with 10 versions of a spell:

https://github.com/ash47/LegendsOfDota/blob/master/lod_game/scripts/vscripts/spellfixes.lua#L536-L556

It also means we need 10 copies of the text and 10 copies of the ability in memory!

**Comment by leopupin** [comment]
Well it was an idea long time without looking at source.... anyway, it would be so gamebreaking that the already crazyness level would fly high

**Comment by leopupin** [comment]
Well, it is good at it is, i only though this were simplier cause I assumed that you used something like spells_effect = (base+level*level_effect)*multiplier but now it don't looks so simple anymore =/, anyway thanks for more than fast response =)

**Comment by ash47** [comment]
Have a look at scripts/NPC/NPC_abilities_custom.txt in folder you installed into addons.

**Comment by leopupin** [comment]
WoW, so even using this don't make it easier... Well, dunno why I though you wouldn't do this way already... Anyway nice job with the mod I really love it!

**Comment by ash47** [comment]
You can't just magically edit values, values need to be hard coded
