### ISSUE TITLE
FPS drop over time

### ISSUE THREAD

**Issue by Jexah** [ash47/LegendsOfDota#5]
Big FPS drop as time goes on. Perhaps too many skills precached, and not being freed up after use?

**Comment by ash47** [comment]
Hoping this is fixed in the new version, but, it remains to be seen, I guess...

**Comment by ash47** [comment]
Apparently fixed  in the new version <3

**Comment by Jexah** [comment]
Still occurs.

**Comment by ash47** [comment]
I think I  fixed this, I found out I was using the timing API incorrectly by mistake XD

so, each LoD instance, I made a new timer that fired evert 100ms, and did some heavy work. What I wanted to do was fire a timer once after a certain event, after 100ms, not every 100ms, ie: if you dont specify the number of repetitions, it will run over and over.

Update to the new LoD, and tell me if it's fixed ;)

**Comment by ash47** [comment]
This one is still killing me, I have no freaking clue what could be causing it.

If you hover over skill icons, it seems to happens, and when you open the shop.

Will continue research.
