### ISSUE TITLE
2.3.0 patch problem or just mine?

### ISSUE THREAD

**Issue by ghostlystrike** [ash47/LegendsOfDota#50]
so i just used 2.3.0 ( latest ) entire day, every things ok untill game over and i want start new game again. Dota2 client just crash and Closed! but server give me a message about network dropped or some thing like that, than i have to wait like 2-3 mins till server got restart itself, 

than i have to try over and over again to connect again and many times it crashes! 

btw, i've tested on your servers (lod.ash47.net:27015-6-7-8) also, same results

i had not this problem in 2.2.6

so is it only my problem or?

thanks in advance

**Comment by ghostlystrike** [comment]
STEAMAUTH : client **** received failure code6
Dropped *** from server <10>: Network _disconnected_ ....
this is exact message from server

**Comment by ghostlystrike** [comment]
Problem still exist in 2.3.1

**Comment by ash47** [comment]
Should be fixed now <3

**Comment by ghostlystrike** [comment]
your the best mate !<3
