### ISSUE TITLE
Improve error messages during spell picking

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#54]
When picking Phantom Lancer Juxtapose, it is wrongly mentioned that you need Doppelganger as well to work. It works with any illusion

Also, when picking Lone Druid bear form. Please put a warning that it will give -420 range or something and will disable your melee hero's auto attacks

**Comment by ash47** [comment]
There is a warning

**Comment by Veroalla** [comment]
My bad then. Outdated info on my part. It's just that I saw someone do that today lol

**Comment by ash47** [comment]
Most people don't read it. Juxtapose issue will be fixed when workshop tools update
