### ISSUE TITLE
Lobby Explorer/in-game settings Settings

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#55]
Source 2: Changing the settings pre-game and then launching the game resets all settings to default.
Nothing I enabled in the lobby explorer settings worked.

Also the new settings screen in-game is covering up the chat box in source 2

**Comment by Veroalla** [comment]
And the max level dropdown is too long and gets past the screen, can't pick 100 level limit

**Comment by ash47** [comment]
Max level issue is fixed, it's meant to cover up part of the chat, perhaps I should implement tabs, or something, to make option selection easier?

**Comment by Veroalla** [comment]
Yeah,  Tabs is a good idea, but make the tabs vertical, fits the layout better.

Another solution would be to make it into an "accordion" style [similar to this](http://www.freeactionscript.com/2009/10/simple-accordion-menu/)
That would be badass and less cluttered.
