### ISSUE TITLE
lod_toolkit.smx not delivered with distribution

### ISSUE THREAD

**Issue by leopupin** [ash47/LegendsOfDota#58]
Only informing that lod_toolkit.smx is not being delivered with the lod main file (don't know if intended)

**Comment by ash47** [comment]
Weird. Probably something wrong with my compiler, will fix for the next release :)

**Comment by ash47** [comment]
You can always just download it from the repo

**Comment by leopupin** [comment]
Yes, I did it, and as a matter of fact, now it's working great, tried some games, and none crashed =)

**Comment by paralin** [comment]
You should probably title this "lod_toolkit.smx not delivered with distribution" haha

**Comment by leopupin** [comment]
Nice suggestion =)

**Comment by ash47** [comment]
Fixed!
