### ISSUE TITLE
source 2 crash on entry

### ISSUE THREAD

**Issue by Veroalla** [ash47/LegendsOfDota#60]
The host always crash if he/she presses the enter button directly when it appears, before anyone else.

You will enter the game with your hero, but will shortly crash right after. The host always crash if he/she does that. I tried it with my laptop too.

Fix: Press enter after 1-2 secs, then pray to God it doesn't crash.

Edit: I think this happens with all Source 2 games? I'm getting unsure now

**Comment by ash47** [comment]
I need more details, when you say "enter button", do you mean the button you press to select a hero, then it changes to enter battle?

**Comment by Veroalla** [comment]
Yes exactly as you described it!

**Comment by ash47** [comment]
Does it happen with 1 vs 1? How many players do I need in order to
reproduce it?

**Comment by Veroalla** [comment]
It happens with 3vs3 and more players from my experience, and with 2vs2 as well (don't exactly recall, only did 2vs2 once)

**Comment by ash47** [comment]
I'll see if I can reproduce on the weekend

**Comment by Veroalla** [comment]
I've started to disable courier. Game doesn't seem to crash so far (2-3 games)
Could you troubleshoot that?

P.S.: Pudge Rot can't be toggled on anymore, in ANY multiplier mode
