### ISSUE TITLE
Bugs 

### ISSUE THREAD

**Issue by onlybiscuit** [ash47/LegendsOfDota#65]
Some matches in reborn doesnt show the settings menu host/player and i once couldnt enter the match and i chose my hero and i clicked enter battle but nothing happened , my friend joined but i couldnt :disappointed: hope you can fix that and thanks for the awesome mod :smile:

**Comment by ash47** [comment]
Yep, I am aware, I'm going to start fixing up LoD today :)

**Comment by ash47** [comment]
Hopefully this is fixed now, if not, new UI will fix this.
