### ISSUE TITLE
Banning ui locks chat and sometimes doesn't switch to picking phase locking player

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#67]
Banning ui locks chat and sometimes doesn't switch to picking phase locking player - I've got locked twice when trying to play in reborn like this. Couldn't say anything and couldn't leave banning mode while everyone wanted me to toggle ready.

**Comment by ash47** [comment]
Really weird XD, again, looking into this, I'm going to decouple LoD from the dota 2 UI, so, hopefully that will fix this issue

**Comment by ash47** [comment]
Will be fixed with the new UI, not going to fix this issue with the current UI
