### ISSUE TITLE
Simplify and standardize mode to make it more mainstream and prevent disconnects in reborn

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#68]
Currently there is too much settings to pick from for the host and people don't want to wait not knowing if it even works or is it blocked. Please set some default options and disable host/admin selection phase + banning phase so players jump right into the picking phase.

Set options as you wish but please block trolling combo's or something. After that let the community talk over the settings and combo bans rather than wasting time of each round on setting up everything. That's what you should do if you want to make the mod mainstream.

Also current ability draft system is quite nice except for the amount of skills to pick from - if its possible it would be nice to mod over AD queue just enabling picking from all heroes while maintaining the skill countering possibility.

**Comment by ash47** [comment]
That's the thing though, it has default options -- It defaults to what I would consider reasonable settings. Again, the option selection screen is something I want to rebuild using panorama ASAP

**Comment by ash47** [comment]
Ok, I can have it show "Option Presets" dropdown, which will have a bunch of fun preset combos.

I can then have a "customize" button  which allows players to customise to their will

**Comment by kacperpl1** [comment]
Yeah, that would do - like max make 5 things to set and 15 - 30 seconds to select them for host.

How about the other stuff? If you're building new UI you could base the picking system on Ability Draft just adding those presets + making the pool of all skills.

**Comment by ash47** [comment]
Again, will be fixed with a new UI, thanks for the input :D
