### ISSUE TITLE
Tutorial dialogs cannot be closed when banning/picking phase is on and block using chat.

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#69]
Can't use chat or close tutorial dialog that is in the background when in banning/picking phase.

Would be nice to completely remove dialogs after host selected settings.

**Comment by ash47** [comment]
I don't know what tutorial dialogs are, I need a screenshot?

**Comment by kacperpl1** [comment]
I mean those few windows that say what to do in LoD when you enter the match when host picks settings and you have to click OK to close them.

**Comment by ash47** [comment]
Oh. I dont really care to be honest, those will be gone soon anyways, once I'm done building the new UI :)

**Comment by kacperpl1** [comment]
Cool, It's just a bug that made chatting impossible and irritating when you couldn't do a thing because other bugs and people flamed over.

If there's anything like info on how to play it would be good to post this info on the workshop page visible in reborn + add screenshots with detailed description

**Comment by kacperpl1** [comment]
Here are the screenshots with "Select Hero" tutorial dialog open in the background - I can't get to close it before match settings pop out.
http://i.imgur.com/pmTLB61.jpg
http://i.imgur.com/TAy2tsD.jpg

**Comment by ash47** [comment]
They aren't covering the LoD UI, so, I don't really care. This will be fixed with a new UI anyways.

**Comment by kacperpl1** [comment]
This is the problem that those are in the background so I cannot close them. Also because those are open I cant write anything in the chat. I'm having this all the time.

Would be nice if you could simply disable those in old ui for now.

**Comment by ash47** [comment]
Oic, well, not much I can do, and they shouldn't only show up once, right?

**Comment by kacperpl1** [comment]
I'm getting those all the time and I can't close the last one since it spawns either too late or I'm not fast enough to close it.

**Comment by ash47** [comment]
Do you get any during the team picking phase?

**Comment by kacperpl1** [comment]
They spawn when i get in the game - I get few seconds to see them and try to close but when LoD settings for admin are shown they stay in the background and I can't close them. They stay that way until the LoD ui is closed after picking phase.

I think I'm not the only one with a problem because not many people are writing anything in the chat.

**Comment by ash47** [comment]
Do you see any during the team selection?

**Comment by kacperpl1** [comment]
I'm sorry, didn't get that. No, it spawns after that when you're already in the game/picking ui as shown on screens i sent, not in the reborn lobby UI.
