### ISSUE TITLE
how contribute "russian" translation and what string i have to translate?

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#71]
hi, ty for keeping this mode up, but how contribute "russian" translation and what string i have to translate?

**Comment by ash47** [comment]
It's kind of CRAZY, but, here is the english file:

https://github.com/ash47/LegendsOfDota/blob/master/script_generator/CUSTOM/addon_english.txt

Note: You _need_ to save the russian file as UNICODE! The english file there is NOT saved as unicode!

**Comment by ohos** [comment]
fuck yeah, i did it, here is russian file saved in notepad++ with Unicode without BOM https://yadi.sk/d/ZdtTHzRvhNP2t

i also found few strings to improve:

lock options, maybe better call it "End selection"?

"easy mode" maybe better call it "fast mode"? because it doesn't really make game easy, it just speed up gameplay for all

"bonus gold" isn't really bonus, because it replace 600 starting gold with selected amount, so i renamed it on russian to just "starting gold"

**Comment by Veroalla** [comment]
I think Lock Options is fine, maybe end selection sounds better in Russian

Easy mode is like a universal explanation used by other mods too. Can't
change it now.

Bonus gold actually is bonus, it's default gold + bonus gold. Selecting 250
bonus gold gives you 825 starting gold.

**Comment by ohos** [comment]
ty for explanation and timer on UI, already saw ^^, tell me when you add this translation, so i can try it in game and see if something wrong

**Comment by ash47** [comment]
It's used.

**Comment by ohos** [comment]
uploaded updated string, replace pls, same link, new file https://yadi.sk/d/ZdtTHzRvhNP2t

**Comment by ohos** [comment]
new version here https://yadi.sk/d/ZdtTHzRvhNP2t (same link, new file)
