### ISSUE TITLE
[BUG] free curier isn't bound to curier hotkeys

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#74]
[BUG] free curier isn't bound to curier hotkeys, when i have item bought and press curier hotkey "delivery" it says "nothing to delivery" even when free curier selected

**Comment by ash47** [comment]
Sounds like a reborn issue, the way that plugin works is by giving you a currior and making you activate it...

**Comment by ohos** [comment]
yes, it's in reborn, because i didn't play this mode in normal dota, so everything i post only belong to reborn ^^

**Comment by ohos** [comment]
also i have an idea for free curier, seems it gives flying curier immedialetly, so would be better if "upgrade to flying curier" would cost 0, then people can't bypass 3 minutes wait before curier become flying, in this case better set default free curier to "walking"

**Comment by ash47** [comment]
The option is disabled for now.

**Comment by ash47** [comment]
This option has been removed, this issue is no longer needed.
