### ISSUE TITLE
is zombie survival mode ready?

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#75]
found in strings during translation

"desEventMatch"						"Event Match"
		"hintEventMatch"					"Survival:\nZombies will spawn and try to kill you, the goal is to survive for as long as possible. The match ends when everyone on a given team is dead at the same time."
		"lod_survival"						"<font color=\"#EB4B4B\">Survival game mode was loaded! The aim is to survive for as long as possible. Zombies will spawn and try to kill you, pick lots of AoE, life steal, and regen!</font>"

but i didn't saw this anywhere when played

**Comment by ash47** [comment]
Its in there, but, disabled for now

**Comment by ash47** [comment]
This is now an issue.
