### ISSUE TITLE
Confusing spells amounts

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#76]
"hintMaxSkills"	"The max number of regular abilities you can pick."
and
"hintMaxUlts" "The max number of ultimate abilities you can pick."

these strings miss tip that your hero can't exceed 6 slots for abilities and % of ability slots can just hold both regular and ults, if i understood right in 6 regular and 6 ults there will be 6 slots allowing both spell type (regular or ults), in setting of 12 regular and 2 ults it would be 6/1 (only one slot for both spells, right?)

maybe better give instead 3 option:

regular
either
ults

to clarify things? in this case would be also cool if amount in each drop down doesn't exceed 6, for example

if i select 3 regular and 3 either, ults drop down don't give me options because 3+3 already 6

**Comment by ash47** [comment]
either is a calculated value and doesnt need to exist.

**Comment by ohos** [comment]
yeah i understand how it made, but it really was confusing for me before friend investigated it, guess described method can clarify things for many people, but it's your mode, your decision any way :3

while preparing ru stranslation i just extended description with example

**Comment by ash47** [comment]
Your suggestion is pretty stupid, a better solution would be to display a sample, so you can see that 4 slots are regular and two are both

**Comment by ohos** [comment]
your way with example good too, my suggestion comes just from idea to remove confusing and make things clear, nothing more :P

**Comment by ash47** [comment]
This doesn't need to be open.
