### ISSUE TITLE
Extra ability points

### ISSUE THREAD

**Issue by SunbleachedAngel** [ash47/LegendsOfDota#78]
I suggest to add an option to skill attributes not only ten times, because when you have only 5 skills and host made max level 100 after level 29 you are just going with extra ability points being an eyesore.

**Comment by ash47** [comment]
This is an obvious suggestion but I am unable to do this, I am probably going to just remove extra points eventually

**Comment by ohos** [comment]
for me that 100 lvls option only for cases of more stats for each lvl and long games with standart resurrections time, so if someone bypass lvl 25 he will resurrect longer and there would be enough time to push

**Comment by ash47** [comment]
Try doubled skills mode with 12 slots, that usually uses 96 ability points,
with 4 going into attribute bonuses

**Comment by Veroalla** [comment]
The custom game HAM solved this by enabling you to lvl your stats up to 20
times.

**Comment by ash47** [comment]
Interesting, no idea how this works, link me and I can probably work out how

**Comment by Veroalla** [comment]
Link: http://steamcommunity.com/sharedfiles/filedetails/?id=430075688
I quote: "heroes can level up to 35 and put up to 20 points in stats"

**Comment by ash47** [comment]
After 7 months in development, hopefully it will have been worth the weight.

This has been added.
