### ISSUE TITLE
Disable/Remove Extra Time button ASAP

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#79]
At this point people keep choosing spells over and over and its really annoying to the point where others leave the match. Please disable or remove this option ASAP to enforce quicker matches

**Comment by kacperpl1** [comment]
Also please remove extra time from banning phase - that's the most annoying thing that happens all the time

**Comment by ash47** [comment]
Made it so you can only request upto one minute extra per team during the picking phase only. Once someone locks during the banning phase, they will stay locked.

Banning phase is now 90 seconds, picking phase is now 2 minutes, upto 4 minutes if both teams want more time.
