### ISSUE TITLE
[reborn] Meepo ult broken

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#81]
Since 21 june meepo's ult won't work, clone doesn't have speels learned, doesn't share stats and die separatly, also clones doesn't share items.

**Comment by kacperpl1** [comment]
+1 to removing/blocking meepo ulti by default because of bugs and being over powered.

**Comment by ohos** [comment]
i think it's fine to ban meepo with just 1 ban per player or just host bans, then you can ban only meepo's ult

the only problem is - broken ult, i usually ban it just to prevent bug for people because they don't know

**Comment by ash47** [comment]
It will be auto banned after the update rolls out, will look into this when I have time.
