### ISSUE TITLE
[reborn] nyx's borrow + aftershock = infinite stun, pls add it to troll combos

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#82]
[reborn] nyx's borrow + aftershock = infinite stun, pls add it to troll combos

**Comment by ash47** [comment]
XD

Will add :)

**Comment by zerodrake** [comment]
ash pls, i pioneered/engineered this build and i want it to stay! i wanna retain an op build not in troll comboes that reminds me of d2modd.in's multicast black hole and death ward shenanigans! (no for srs burrow jsut needs to go, it's useless without nyx's other abilities, of which i doubt many people take, since burrow does not affect other spells)

**Comment by ash47** [comment]
I don't understand? You realize you can just allow troll combos right?

**Comment by ash47** [comment]
You can actually do multicast black hole and death ward now, although they will be deleted if you stop channeling now

**Comment by ash47** [comment]
Can you actually move? I'm not sure how OP this will be if you can't move...

**Comment by zerodrake** [comment]
you can only move in burrow if you have moving spell i.e. timber chain, skewer, waveform, rolling boulder, you cna onlyt leave burrow if you use vendetta

**Comment by zerodrake** [comment]
and i was making a joke, i think it should be fixed i.e. balck hole/deaht awrd used to be, where it isn't possible to do. thinking maybe place a cooldown on burrow, having burrow only usable if vendetta is levelled. but idk if those are possible on your side.

**Comment by MrMark1337** [comment]
I am giggles, and I made a video_https://www.youtube.com/watch?v=sFrIPrYU-Kc showing how it works.

**Comment by ohos** [comment]
with borrow you can move with just blink skill lol

**Comment by ash47** [comment]
Banned.
