### ISSUE TITLE
[reborn] wrong skill icons during pick

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#84]
sometime randomly happen bug, so when you pick spell it can show wrong icon, for example i took aftershock, but it show me void's icon https://yadi.sk/i/CkmepQL3hRFRD

bug happen randomly on reborn, when it happen you don't see blocked spells because seems they think you have another spell, but when you try pick it will say about block, like aftershock and ball lightning

**Comment by ash47** [comment]
Yep, the issue is, there is an encoding put onto the spells to protect the other team from knowing what it is, for some reason, it is decoding incorrectly for you.

**Comment by ash47** [comment]
For the record, I don't really care -- The picking interface is being redesigned and built from the ground up using the new system, so, not going to bother fixing this, it will resolve once the new UI rolls out.

**Comment by louiscardinal** [comment]
I believe this bug occurs when you shuffle players or move slots before you lock in players.

**Comment by ash47** [comment]
Oh, very interesting! Thanks VERY much, I now have a way to investigate this. You have no idea how much it helps to have a LEAD!

**Comment by ohos** [comment]
a friend told when bug occur small spell icons under hero icon on top of screen still show correct icons

**Comment by ash47** [comment]
I think this has been fixed.
