### ISSUE TITLE
loading bug dota reborn

### ISSUE THREAD

**Issue by 5topwutxrm** [ash47/LegendsOfDota#85]
Sry for my grammar but i found a bug. Today i hosted 5-6 games, 1st game were nice but in the second i had a bug 1) http://iscr.ru/photo/1435134425_20150624_00001.jpg when player left the game, then i tried to close this game or disconnect, but my colsole were disabled, not sure why, so i hosted 3rd game without restarting dota and then i had this bug 2) http://iscr.ru/photo/1435134545_20150624_00002.jpg http://iscr.ru/photo/1435134575_20150624_00003.jpg (in the second screenshot i started a game alone) (i hosted and 9 ppl connected to my lobby and game automaticaly started). I dont wanted to play alone :) so i restarted dota after this try but ppl left the game again and i had same bugs 1st then 2nd, i restarted dota again and i fixed it bec everyone loaded after 3rd restart. Please fix it and don't judge my grammar too harshly.

**Comment by ash47** [comment]
You're linking me to multiple screenshots, link me to a specific one if you
want me to look

**Comment by 5topwutxrm** [comment]
@ash47 changed links.

**Comment by ash47** [comment]
Weird stuff XD

**Comment by ash47** [comment]
This seems to be fixed?
