### ISSUE TITLE
Witchcraft doesn't lower mana cost

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#88]
Witchcraft doesn't lower mana cost of spells plus it doesn't update visually the cooldown in the skill tooltip

**Comment by ash47** [comment]
This is correct.

**Comment by ash47** [comment]
I was meaning to do the manacost thing, no clue how to update the tooltip s

**Comment by kacperpl1** [comment]
You mean you intended to do it like that? Can you update the witchcraft tooltip so it doesn't say it lowers the mana cost?

**Comment by ash47** [comment]
I intended to make it refund your mana

**Comment by kacperpl1** [comment]
You intended? So it's not working yet?

Anyway I've played with witchcraft + quill spray + sticky napalm - both spells took all mana with no refunds.

**Comment by ash47** [comment]
Yes, I am aware, to clarify: When I was coding witchcraft, I wanted to make
ti refund the mana, however, I got wrapped up with playing with the
cooldown part, then ended out moving onto other features and forgot about
it. I'll likely fix it eventully <3
