### ISSUE TITLE
[request] Disable picking same hero by multiple players

### ISSUE THREAD

**Issue by kacperpl1** [ash47/LegendsOfDota#89]
When multiple players get same hero it gets messy and sometimes it may be OP. For example if multiple players take void and only one of them has the chronosphere, thanks to innate all of them should be able to walk inside. The other things is a mess in addressing who's who - in normal dota you tend to address players by their heroes  + having multiple players with a same hero in a teamfight is a messy thing.

**Comment by ash47** [comment]
What do you want me to do? People complain even more if they can't pick the
hero they want.

**Comment by kacperpl1** [comment]
Huh, that's quite a problem. With all heroes possible to pick doing it like AP where first to pick gets the player is the only thing I can think of. Except for innates and few heroes like huskar which is both ranged and strength all others are just the looks and stat gain I think.

**Comment by ash47** [comment]
Huskar being a ranged strength hero won't be an issue for much longer ;)

**Comment by ash47** [comment]
It's possible to tint heroes, I could do that...

**Comment by kacperpl1** [comment]
It's not about tinting heroes - moba has it's unique thing about representing players with their heroes.

Trust me, I'm a game developer myself :) - it's not about painting the colours, that would be just a prosthetic half-measure.

**Comment by ash47** [comment]
I have had HUGE amounts of FUUUUNNN working as a team and picking the same heroes! Most memorable was when my entire team waiting until the last moment, and all picked faceless void. We also had meepo's teleport skill. When ever someone was in trouble, they would ping the minimap, and we would all use meepo's poof to teleport to the person, and one of us would drop a chrono, and we'd all kill the person that was attacking. It was ammmaazzzinnng!

Needless to say, I could add an option that disables same hero picking, but it's just going to piss people off.

**Comment by kacperpl1** [comment]
Some people will get pissed but you can't make everyone happy.

As for the fun you've had - I agree it can be nice when you're playing with people that won't take their toys when seeing stuff like that but at this point it's not the case.

Think about standardising the mode and making it balanced and competitive so the match lasts significantly more than the amount of time taken by match making and picking skills.

Once again - "adding an option/making a system for that" is a programmer's way - think about it like a game designer and just make it work by default :)

**Comment by ash47** [comment]
You're right, I can't make everyone happy, and you are the first person to
ever complain about this, I didn't even consider that it could even be an
issue until right now.

**Comment by kacperpl1** [comment]
yeah, that's just a thing you might think about making the mode more common people friendly. I just think it would help. It's not something game breaking but it's messy and with innates like void's it gives chance to making OP team disabling whole enemy team which will end up with ragequits.

**Comment by ash47** [comment]
This is implemented, will roll out later <3
