### ISSUE TITLE
Add an option for unique hero picks only

### ISSUE THREAD

**Issue by louiscardinal** [ash47/LegendsOfDota#91]
This means that only one of each hero can be taken, instead of multiple of the same hero; add the option for unique hero picks in the rules setup. This way hosts have the option of allowing or disallowing duplicate hero choices.

**Comment by kacperpl1** [comment]
This is a duplicate of https://github.com/ash47/LegendsOfDota/issues/89

**Comment by louiscardinal** [comment]
Yes but my post facilitates flexibility as a setting you can turn on or off, while your post just suggested a flat out change that is guaranteed to make some people in the community mad.

**Comment by ash47** [comment]
This is implemented, and will roll out later today.
