### ISSUE TITLE
[reborn] please disable hero selection before spell pick :D

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#92]
[reborn] please disable hero selection before spell pick :D

with 10% chance there's someone noob picking before spell pick and breaking his spells when game begin

**Comment by Veroalla** [comment]
If the new UI doesn't fix this issue, maybe Ash should make it so that it's
not apparent that you can pick heroes until after spell picking?​

**Comment by SirVelocifaptor** [comment]
What I've encountered is the inability to pick any spells in all pick, and I end up only being able to pick hero.

**Comment by ash47** [comment]
This will likely be fixed in the future, but, it's not high priority right now.
