### ISSUE TITLE
[reborn] borrow skill don't have unborrow

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#96]
borrow skill don't have unborrow, so please add it and make additional note that AM's and QOP's blinks doesn't work while borrowed

**Comment by ash47** [comment]
I didn't know there was an un burrow, cool!

**Comment by ohos** [comment]
sure it was here since borrow was added, when nyx borrow this skill replaced with unborrow

**Comment by ohos** [comment]
http://dota2.gamepedia.com/Nyx_Assassin

unborrow

**Comment by ash47** [comment]
Fixed, will rollout later today
