### ISSUE TITLE
[bug] show enemy pick broken (reborn)

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#97]
show enemy pick broken (reborn)

**Comment by SunbleachedAngel** [comment]
More details please

**Comment by ohos** [comment]
Enemy picked spells doesn't show on hero icons at top of screen, there always stay ? icons when "hide enemy pick" set to "no"

**Comment by ash47** [comment]
Ah, well, I will ignore this for now, as, this will be fixed when the new UI rolls out anyways :)

**Comment by ash47** [comment]
This won't be fixed in the current UI.
