### ISSUE TITLE
[bug] active effects of items as spells totaly broken (reborn)

### ISSUE THREAD

**Issue by ohos** [ash47/LegendsOfDota#98]
active effects of items as spells totaly broken

midas: only trigger cd on spell
shadow blade: doesn't trigger cd, but consume mana
dagger: only trigger cd

p.s. dota 2 reborn

**Comment by ash47** [comment]
Yep, worked in s1, will look into it either tonight or tomorrow

**Comment by Veroalla** [comment]
Can you remove "active effects" dropdown at least? It's totally useless

**Comment by ash47** [comment]
Probably going to completely remove items as spells.
