### ISSUE TITLE
[Reborn]Hero/Creeps + Ancient creeps didn't work correctly

### ISSUE THREAD

**Issue by minecraftpx3** [ash47/LegendsOfDota#99]
In LegendsOfDota I played few days ago it have a bug where it cannot be end and heros and creeps are not visible. And in the late game creeps are targetting for the Ancient instead of the inner level of the tower. Heros are also unable to attack the enemy towers before the game try to attack the ancient so it result in the way that the game cannot end because the ancient in invulnuerable intul the inner towers are destroyed which is impossible. I consider this is as a bug and I would want the developer to fix this. Thx for reading.

**Comment by ash47** [comment]
I need to know for to reproduce otherwise this is useless information. It
has never happened to me, how do I even go about finding this issue?

**Comment by ohos** [comment]
didn't saw such bug, try verify your dota files from steam client with right mouse click, properties

**Comment by minecraftpx3** [comment]
Is this kind of related to time of the game? Because I played with my friend for almost an hour on that match.

**Comment by ash47** [comment]
No idea how to reproduce this, so, can't fix it.
